
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xospipsv.h"

/*
* The configuration table for devices
*/

XOspiPsv_Config XOspiPsv_ConfigTable[XPAR_XOSPIPSV_NUM_INSTANCES] =
{
	{
		XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_OSPI_0_DEVICE_ID,
		XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_OSPI_0_BASEADDR,
		XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_OSPI_0_OSPI_CLK_FREQ_HZ,
		XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_OSPI_0_IS_CACHE_COHERENT,
		XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_OSPI_0_OSPI_MODE
	}
};


