#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

/* Definition for CPU ID */
#define XPAR_CPU_ID 0U

/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_CORTEXR5_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_CORTEXR5_0_CPU_CLK_FREQ_HZ 600000000


/******************************************************************/

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_CORTEXR5_0 */
#define XPAR_CPU_CORTEXR5_0_CPU_CLK_FREQ_HZ 600000000


/******************************************************************/

 /* Definition for PSS REF CLK FREQUENCY */
#define XPAR_PSU_PSS_REF_CLK_FREQ_HZ 33333000U

#include "xparameters_ps.h"

/* Platform specific definitions */
#ifndef versal
#define versal
#endif

 
/******************************************************************/
#define STDIN_BASEADDRESS 0xFF010000
#define STDOUT_BASEADDRESS 0xFF010000

/******************************************************************/

/* Definitions for driver BRAM */
#define XPAR_XBRAM_NUM_INSTANCES 1U

/* Definitions for peripheral ULP_PLRAM_CTRL */
#define XPAR_ULP_PLRAM_CTRL_DEVICE_ID 0U
#define XPAR_ULP_PLRAM_CTRL_DATA_WIDTH 512U
#define XPAR_ULP_PLRAM_CTRL_ECC 0U
#define XPAR_ULP_PLRAM_CTRL_FAULT_INJECT 0U
#define XPAR_ULP_PLRAM_CTRL_CE_FAILING_REGISTERS 0U
#define XPAR_ULP_PLRAM_CTRL_UE_FAILING_REGISTERS 0U
#define XPAR_ULP_PLRAM_CTRL_ECC_STATUS_REGISTERS 0U
#define XPAR_ULP_PLRAM_CTRL_CE_COUNTER_WIDTH 0U
#define XPAR_ULP_PLRAM_CTRL_ECC_ONOFF_REGISTER 0U
#define XPAR_ULP_PLRAM_CTRL_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_ULP_PLRAM_CTRL_WRITE_ACCESS 0U
#define XPAR_ULP_PLRAM_CTRL_S_AXI_BASEADDR 0x20204000000U
#define XPAR_ULP_PLRAM_CTRL_S_AXI_HIGHADDR 0x2020401FFFFU
#define XPAR_ULP_PLRAM_CTRL_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_ULP_PLRAM_CTRL_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU  


/******************************************************************/

/* Canonical definitions for peripheral ULP_PLRAM_CTRL */
#define XPAR_BRAM_0_DEVICE_ID XPAR_ULP_PLRAM_CTRL_DEVICE_ID
#define XPAR_BRAM_0_DATA_WIDTH 512U
#define XPAR_BRAM_0_ECC 0U
#define XPAR_BRAM_0_FAULT_INJECT 0U
#define XPAR_BRAM_0_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_0_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_0_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_0_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_0_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_0_ECC_ONOFF_RESET_VALUE 0U
#define XPAR_BRAM_0_WRITE_ACCESS 0U
#define XPAR_BRAM_0_BASEADDR 0x20204000000U
#define XPAR_BRAM_0_HIGHADDR 0x2020401FFFFU
#define XPAR_BRAM_0_CTRL_BASEADDR 0xFFFFFFFFU  
#define XPAR_BRAM_0_CTRL_HIGHADDR 0xFFFFFFFEU  


/******************************************************************/

/* Definitions for driver CFRAME */
#define XPAR_XCFRAME_NUM_INSTANCES 1

/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_CFI_CFRAME_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_CFI_CFRAME_0_DEVICE_ID 0
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_CFI_CFRAME_0_BASEADDR 0xF12D0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_CFI_CFRAME_0_HIGHADDR 0xF12D0FFF


/******************************************************************/

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_CFI_CFRAME_0 */
#define XPAR_XCFRAME_0_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_CFI_CFRAME_0_DEVICE_ID
#define XPAR_XCFRAME_0_BASEADDR 0xF12D0000
#define XPAR_XCFRAME_0_HIGHADDR 0xF12D0FFF


/******************************************************************/

/* Definitions for driver CFUPMC */
#define XPAR_XCFUPMC_NUM_INSTANCES 1

/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_CFU_APB_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_CFU_APB_0_DEVICE_ID 0
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_CFU_APB_0_BASEADDR 0xF12B0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_CFU_APB_0_HIGHADDR 0xF12BFFFF


/******************************************************************/

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_CFU_APB_0 */
#define XPAR_XCFUPMC_0_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_CFU_APB_0_DEVICE_ID
#define XPAR_XCFUPMC_0_BASEADDR 0xF12B0000
#define XPAR_XCFUPMC_0_HIGHADDR 0xF12BFFFF


/******************************************************************/

/* Definitions for driver CLK_WIZ */
#define XPAR_XCLK_WIZ_NUM_INSTANCES 2

/* Definitions for peripheral BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_00_HIERARCHY_CLKWIZ_ACLK_KERNEL_00 */
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_00_HIERARCHY_CLKWIZ_ACLK_KERNEL_00_DEVICE_ID 0
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_00_HIERARCHY_CLKWIZ_ACLK_KERNEL_00_BASEADDR 0x80032000
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_00_HIERARCHY_CLKWIZ_ACLK_KERNEL_00_HIGHADDR 0x80032FFF
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_00_HIERARCHY_CLKWIZ_ACLK_KERNEL_00_ENABLE_CLOCK_MONITOR 0
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_00_HIERARCHY_CLKWIZ_ACLK_KERNEL_00_ENABLE_USER_CLOCK0 0
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_00_HIERARCHY_CLKWIZ_ACLK_KERNEL_00_ENABLE_USER_CLOCK1 0
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_00_HIERARCHY_CLKWIZ_ACLK_KERNEL_00_ENABLE_USER_CLOCK2 0
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_00_HIERARCHY_CLKWIZ_ACLK_KERNEL_00_ENABLE_USER_CLOCK3 0
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_00_HIERARCHY_CLKWIZ_ACLK_KERNEL_00_REF_CLK_FREQ 100
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_00_HIERARCHY_CLKWIZ_ACLK_KERNEL_00_USER_CLK_FREQ0 100
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_00_HIERARCHY_CLKWIZ_ACLK_KERNEL_00_USER_CLK_FREQ1 100
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_00_HIERARCHY_CLKWIZ_ACLK_KERNEL_00_USER_CLK_FREQ2 100
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_00_HIERARCHY_CLKWIZ_ACLK_KERNEL_00_USER_CLK_FREQ3 100
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_00_HIERARCHY_CLKWIZ_ACLK_KERNEL_00_PRECISION 1
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_00_HIERARCHY_CLKWIZ_ACLK_KERNEL_00_ENABLE_PLL0 0
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_00_HIERARCHY_CLKWIZ_ACLK_KERNEL_00_ENABLE_PLL1 0
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_00_HIERARCHY_CLKWIZ_ACLK_KERNEL_00_PRIM_IN_FREQ 33.333
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_00_HIERARCHY_CLKWIZ_ACLK_KERNEL_00_NUM_OUT_CLKS 1


/* Definitions for peripheral BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_01_HIERARCHY_CLKWIZ_ACLK_KERNEL_01 */
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_01_HIERARCHY_CLKWIZ_ACLK_KERNEL_01_DEVICE_ID 1
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_01_HIERARCHY_CLKWIZ_ACLK_KERNEL_01_BASEADDR 0x80033000
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_01_HIERARCHY_CLKWIZ_ACLK_KERNEL_01_HIGHADDR 0x80033FFF
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_01_HIERARCHY_CLKWIZ_ACLK_KERNEL_01_ENABLE_CLOCK_MONITOR 0
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_01_HIERARCHY_CLKWIZ_ACLK_KERNEL_01_ENABLE_USER_CLOCK0 0
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_01_HIERARCHY_CLKWIZ_ACLK_KERNEL_01_ENABLE_USER_CLOCK1 0
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_01_HIERARCHY_CLKWIZ_ACLK_KERNEL_01_ENABLE_USER_CLOCK2 0
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_01_HIERARCHY_CLKWIZ_ACLK_KERNEL_01_ENABLE_USER_CLOCK3 0
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_01_HIERARCHY_CLKWIZ_ACLK_KERNEL_01_REF_CLK_FREQ 100
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_01_HIERARCHY_CLKWIZ_ACLK_KERNEL_01_USER_CLK_FREQ0 100
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_01_HIERARCHY_CLKWIZ_ACLK_KERNEL_01_USER_CLK_FREQ1 100
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_01_HIERARCHY_CLKWIZ_ACLK_KERNEL_01_USER_CLK_FREQ2 100
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_01_HIERARCHY_CLKWIZ_ACLK_KERNEL_01_USER_CLK_FREQ3 100
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_01_HIERARCHY_CLKWIZ_ACLK_KERNEL_01_PRECISION 1
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_01_HIERARCHY_CLKWIZ_ACLK_KERNEL_01_ENABLE_PLL0 0
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_01_HIERARCHY_CLKWIZ_ACLK_KERNEL_01_ENABLE_PLL1 0
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_01_HIERARCHY_CLKWIZ_ACLK_KERNEL_01_PRIM_IN_FREQ 33.333
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_01_HIERARCHY_CLKWIZ_ACLK_KERNEL_01_NUM_OUT_CLKS 1


/******************************************************************/

/* Canonical definitions for peripheral BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_00_HIERARCHY_CLKWIZ_ACLK_KERNEL_00 */
#define XPAR_CLK_WIZ_0_DEVICE_ID XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_00_HIERARCHY_CLKWIZ_ACLK_KERNEL_00_DEVICE_ID
#define XPAR_CLK_WIZ_0_BASEADDR 0x80032000
#define XPAR_CLK_WIZ_0_HIGHADDR 0x80032FFF
#define XPAR_CLK_WIZ_0_ENABLE_CLOCK_MONITOR 0
#define XPAR_CLK_WIZ_0_ENABLE_USER_CLOCK0 0
#define XPAR_CLK_WIZ_0_ENABLE_USER_CLOCK1 0
#define XPAR_CLK_WIZ_0_ENABLE_USER_CLOCK2 0
#define XPAR_CLK_WIZ_0_ENABLE_USER_CLOCK3 0
#define XPAR_CLK_WIZ_0_REF_CLK_FREQ 100
#define XPAR_CLK_WIZ_0_USER_CLK_FREQ0 100
#define XPAR_CLK_WIZ_0_USER_CLK_FREQ1 100
#define XPAR_CLK_WIZ_0_USER_CLK_FREQ2 100
#define XPAR_CLK_WIZ_0_USER_CLK_FREQ3 100
#define XPAR_CLK_WIZ_0_PRECISION 1
#define XPAR_CLK_WIZ_0_Enable_PLL0 0
#define XPAR_CLK_WIZ_0_Enable_PLL1 0
#define XPAR_CLK_WIZ_0_PRIM_IN_FREQ 33.333
#define XPAR_CLK_WIZ_0_NUM_OUT_CLKS 1

/* Canonical definitions for peripheral BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_01_HIERARCHY_CLKWIZ_ACLK_KERNEL_01 */
#define XPAR_CLK_WIZ_1_DEVICE_ID XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_ACLK_KERNEL_01_HIERARCHY_CLKWIZ_ACLK_KERNEL_01_DEVICE_ID
#define XPAR_CLK_WIZ_1_BASEADDR 0x80033000
#define XPAR_CLK_WIZ_1_HIGHADDR 0x80033FFF
#define XPAR_CLK_WIZ_1_ENABLE_CLOCK_MONITOR 0
#define XPAR_CLK_WIZ_1_ENABLE_USER_CLOCK0 0
#define XPAR_CLK_WIZ_1_ENABLE_USER_CLOCK1 0
#define XPAR_CLK_WIZ_1_ENABLE_USER_CLOCK2 0
#define XPAR_CLK_WIZ_1_ENABLE_USER_CLOCK3 0
#define XPAR_CLK_WIZ_1_REF_CLK_FREQ 100
#define XPAR_CLK_WIZ_1_USER_CLK_FREQ0 100
#define XPAR_CLK_WIZ_1_USER_CLK_FREQ1 100
#define XPAR_CLK_WIZ_1_USER_CLK_FREQ2 100
#define XPAR_CLK_WIZ_1_USER_CLK_FREQ3 100
#define XPAR_CLK_WIZ_1_PRECISION 1
#define XPAR_CLK_WIZ_1_Enable_PLL0 0
#define XPAR_CLK_WIZ_1_Enable_PLL1 0
#define XPAR_CLK_WIZ_1_PRIM_IN_FREQ 33.333
#define XPAR_CLK_WIZ_1_NUM_OUT_CLKS 1


/******************************************************************/

/* Definitions for driver CSUDMA */
#define XPAR_XCSUDMA_NUM_INSTANCES 2

/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_DMA_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_DMA_0_DEVICE_ID 0
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_DMA_0_BASEADDR 0xF11C0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_DMA_0_HIGHADDR 0xF11CFFFF
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_DMA_0_CSUDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_DMA_1 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_DMA_1_DEVICE_ID 1
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_DMA_1_BASEADDR 0xF11D0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_DMA_1_HIGHADDR 0xF11DFFFF
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_DMA_1_CSUDMA_CLK_FREQ_HZ 0


/******************************************************************/

#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_DMA_0_DMATYPE 1
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_DMA_1_DMATYPE 2
/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_DMA_0 */
#define XPAR_XCSUDMA_0_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_DMA_0_DEVICE_ID
#define XPAR_XCSUDMA_0_BASEADDR 0xF11C0000
#define XPAR_XCSUDMA_0_HIGHADDR 0xF11CFFFF
#define XPAR_XCSUDMA_0_CSUDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_DMA_1 */
#define XPAR_XCSUDMA_1_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_DMA_1_DEVICE_ID
#define XPAR_XCSUDMA_1_BASEADDR 0xF11D0000
#define XPAR_XCSUDMA_1_HIGHADDR 0xF11DFFFF
#define XPAR_XCSUDMA_1_CSUDMA_CLK_FREQ_HZ 0


/******************************************************************/


/* Definitions for peripheral BLP_AXI_NOC_MC */
#define XPAR_BLP_AXI_NOC_MC_C0_DDR_LOW0X4_CPM_PCIE_NOC_0_BASEADDR 0x40000
#define XPAR_BLP_AXI_NOC_MC_C0_DDR_LOW0X4_CPM_PCIE_NOC_0_HIGHADDR 0x7FFFFFFF
#define XPAR_BLP_AXI_NOC_MC_C0_DDR_LOW0X4_CPM_PCIE_NOC_1_BASEADDR 0x40000
#define XPAR_BLP_AXI_NOC_MC_C0_DDR_LOW0X4_CPM_PCIE_NOC_1_HIGHADDR 0x7FFFFFFF
#define XPAR_BLP_AXI_NOC_MC_C0_DDR_LOW0X4_LPD_AXI_NOC_0_BASEADDR 0x40000
#define XPAR_BLP_AXI_NOC_MC_C0_DDR_LOW0X4_LPD_AXI_NOC_0_HIGHADDR 0x7FFFFFFF
#define XPAR_BLP_AXI_NOC_MC_C0_DDR_LOW2X4_CPM_PCIE_NOC_0_BASEADDR 0xC080000000
#define XPAR_BLP_AXI_NOC_MC_C0_DDR_LOW2X4_CPM_PCIE_NOC_0_HIGHADDR 0xC3FFFFFFFF
#define XPAR_BLP_AXI_NOC_MC_C0_DDR_LOW2X4_CPM_PCIE_NOC_1_BASEADDR 0xC080000000
#define XPAR_BLP_AXI_NOC_MC_C0_DDR_LOW2X4_CPM_PCIE_NOC_1_HIGHADDR 0xC3FFFFFFFF

/* Canonicals definitions for NOC DDR to be consumed by MMU/MPU tables in BSP*/
#define XPAR_AXI_NOC_DDR_LOW_0_BASEADDR 0x40000
#define XPAR_AXI_NOC_DDR_LOW_0_HIGHADDR 0x7FFFFFFF

#define XPAR_AXI_NOC_DDR_LOW_2_BASEADDR 0xC080000000
#define XPAR_AXI_NOC_DDR_LOW_2_HIGHADDR 0xC3FFFFFFFF


/******************************************************************/


/* Peripheral Definitions for peripheral BLP_BLP_LOGIC_AXI_BLP_DBG_HUB */
#define XPAR_BLP_BLP_LOGIC_AXI_BLP_DBG_HUB_BASEADDR 0x20105000000
#define XPAR_BLP_BLP_LOGIC_AXI_BLP_DBG_HUB_HIGHADDR 0x201051FFFFF


/* Peripheral Definitions for peripheral BLP_BLP_LOGIC_AXI_FIREWALL_USER */
#define XPAR_BLP_BLP_LOGIC_AXI_FIREWALL_USER_BASEADDR 0x80001000
#define XPAR_BLP_BLP_LOGIC_AXI_FIREWALL_USER_HIGHADDR 0x80001FFF


/* Peripheral Definitions for peripheral BLP_BLP_LOGIC_PF0_BAR_LAYOUT */
#define XPAR_BLP_BLP_LOGIC_PF0_BAR_LAYOUT_BASEADDR 0x20102001000
#define XPAR_BLP_BLP_LOGIC_PF0_BAR_LAYOUT_HIGHADDR 0x20102001FFF


/* Peripheral Definitions for peripheral BLP_BLP_LOGIC_PF1_BAR_LAYOUT */
#define XPAR_BLP_BLP_LOGIC_PF1_BAR_LAYOUT_BASEADDR 0x20202001000
#define XPAR_BLP_BLP_LOGIC_PF1_BAR_LAYOUT_HIGHADDR 0x20202001FFF


/* Peripheral Definitions for peripheral BLP_BLP_LOGIC_SB_REMAP */
#define XPAR_BLP_BLP_LOGIC_SB_REMAP_BASEADDR 0x20102030000
#define XPAR_BLP_BLP_LOGIC_SB_REMAP_HIGHADDR 0x20102030FFF


/* Peripheral Definitions for peripheral BLP_BLP_LOGIC_ULP_CLOCKING_FREQUENCY_COUNTERS_FREQUENCY_COUNTER_ACLK */
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_FREQUENCY_COUNTERS_FREQUENCY_COUNTER_ACLK_BASEADDR 0x80036000
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_FREQUENCY_COUNTERS_FREQUENCY_COUNTER_ACLK_HIGHADDR 0x80036FFF


/* Peripheral Definitions for peripheral BLP_BLP_LOGIC_ULP_CLOCKING_FREQUENCY_COUNTERS_FREQUENCY_COUNTER_ACLK_KERNEL_00 */
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_FREQUENCY_COUNTERS_FREQUENCY_COUNTER_ACLK_KERNEL_00_BASEADDR 0x80034000
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_FREQUENCY_COUNTERS_FREQUENCY_COUNTER_ACLK_KERNEL_00_HIGHADDR 0x80034FFF


/* Peripheral Definitions for peripheral BLP_BLP_LOGIC_ULP_CLOCKING_FREQUENCY_COUNTERS_FREQUENCY_COUNTER_ACLK_KERNEL_01 */
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_FREQUENCY_COUNTERS_FREQUENCY_COUNTER_ACLK_KERNEL_01_BASEADDR 0x80035000
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_FREQUENCY_COUNTERS_FREQUENCY_COUNTER_ACLK_KERNEL_01_HIGHADDR 0x80035FFF


/* Peripheral Definitions for peripheral BLP_BLP_LOGIC_UUID_ROM */
#define XPAR_BLP_BLP_LOGIC_UUID_ROM_BASEADDR 0x20102002000
#define XPAR_BLP_BLP_LOGIC_UUID_ROM_HIGHADDR 0x20102002FFF


/* Peripheral Definitions for peripheral BLP_BLP_LOGIC_XGQ_M2R */
#define XPAR_BLP_BLP_LOGIC_XGQ_M2R_BASEADDR 0x80010000
#define XPAR_BLP_BLP_LOGIC_XGQ_M2R_HIGHADDR 0x80010FFF


/* Peripheral Definitions for peripheral BLP_BLP_LOGIC_XGQ_R2A */
#define XPAR_BLP_BLP_LOGIC_XGQ_R2A_BASEADDR 0x80011000
#define XPAR_BLP_BLP_LOGIC_XGQ_R2A_HIGHADDR 0x80011FFF


/* Peripheral Definitions for peripheral BLP_BLP_LOGIC_XGQ_U2A_0 */
#define XPAR_BLP_BLP_LOGIC_XGQ_U2A_0_BASEADDR 0x402010000
#define XPAR_BLP_BLP_LOGIC_XGQ_U2A_0_HIGHADDR 0x402010FFF


/* Peripheral Definitions for peripheral BLP_BLP_LOGIC_XGQ_U2A_1 */
#define XPAR_BLP_BLP_LOGIC_XGQ_U2A_1_BASEADDR 0x402011000
#define XPAR_BLP_BLP_LOGIC_XGQ_U2A_1_HIGHADDR 0x402011FFF


/* Peripheral Definitions for peripheral BLP_BLP_LOGIC_XGQ_U2A_2 */
#define XPAR_BLP_BLP_LOGIC_XGQ_U2A_2_BASEADDR 0x402012000
#define XPAR_BLP_BLP_LOGIC_XGQ_U2A_2_HIGHADDR 0x402012FFF


/* Peripheral Definitions for peripheral BLP_BLP_LOGIC_XGQ_U2A_3 */
#define XPAR_BLP_BLP_LOGIC_XGQ_U2A_3_BASEADDR 0x402013000
#define XPAR_BLP_BLP_LOGIC_XGQ_U2A_3_HIGHADDR 0x402013FFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_APU_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_APU_0_S_AXI_BASEADDR 0xFD5C0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_APU_0_S_AXI_HIGHADDR 0xFD5CFFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_CORESIGHT_FPD_STM */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_CORESIGHT_FPD_STM_S_AXI_BASEADDR 0xF0B70000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_CORESIGHT_FPD_STM_S_AXI_HIGHADDR 0xF0B7FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_CRF_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_CRF_0_S_AXI_BASEADDR 0xFD1A0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_CRF_0_S_AXI_HIGHADDR 0xFD2DFFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_CRL_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_CRL_0_S_AXI_BASEADDR 0xFF5E0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_CRL_0_S_AXI_HIGHADDR 0xFF8DFFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_CRP_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_CRP_0_S_AXI_BASEADDR 0xF1260000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_CRP_0_S_AXI_HIGHADDR 0xF126FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_FPD_AFI_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_FPD_AFI_0_S_AXI_BASEADDR 0xFD360000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_FPD_AFI_0_S_AXI_HIGHADDR 0xFD36FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_FPD_AFI_2 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_FPD_AFI_2_S_AXI_BASEADDR 0xFD380000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_FPD_AFI_2_S_AXI_HIGHADDR 0xFD38FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_FPD_CCI_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_FPD_CCI_0_S_AXI_BASEADDR 0xFD5E0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_FPD_CCI_0_S_AXI_HIGHADDR 0xFD5EFFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_FPD_GPV_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_FPD_GPV_0_S_AXI_BASEADDR 0xFD700000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_FPD_GPV_0_S_AXI_HIGHADDR 0xFD7FFFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_FPD_MAINCCI_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_FPD_MAINCCI_0_S_AXI_BASEADDR 0xFD000000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_FPD_MAINCCI_0_S_AXI_HIGHADDR 0xFD0FFFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_FPD_SLAVE_XMPU_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_FPD_SLAVE_XMPU_0_S_AXI_BASEADDR 0xFD390000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_FPD_SLAVE_XMPU_0_S_AXI_HIGHADDR 0xFD39FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_FPD_SLCR_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_FPD_SLCR_0_S_AXI_BASEADDR 0xFD610000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_FPD_SLCR_0_S_AXI_HIGHADDR 0xFD61FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_FPD_SLCR_SECURE_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_FPD_SLCR_SECURE_0_S_AXI_BASEADDR 0xFD690000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_FPD_SLCR_SECURE_0_S_AXI_HIGHADDR 0xFD69FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_FPD_SMMU_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_FPD_SMMU_0_S_AXI_BASEADDR 0xFD5F0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_FPD_SMMU_0_S_AXI_HIGHADDR 0xFD5FFFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_FPD_SMMUTCU_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_FPD_SMMUTCU_0_S_AXI_BASEADDR 0xFD800000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_FPD_SMMUTCU_0_S_AXI_HIGHADDR 0xFDFFFFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_LPD_AFI_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_LPD_AFI_0_S_AXI_BASEADDR 0xFF9B0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_LPD_AFI_0_S_AXI_HIGHADDR 0xFF9BFFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_LPD_IOU_SECURE_SLCR_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_LPD_IOU_SECURE_SLCR_0_S_AXI_BASEADDR 0xFF0A0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_LPD_IOU_SECURE_SLCR_0_S_AXI_HIGHADDR 0xFF0AFFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_LPD_IOU_SLCR_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_LPD_IOU_SLCR_0_S_AXI_BASEADDR 0xFF080000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_LPD_IOU_SLCR_0_S_AXI_HIGHADDR 0xFF09FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_LPD_SLCR_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_LPD_SLCR_0_S_AXI_BASEADDR 0xFF410000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_LPD_SLCR_0_S_AXI_HIGHADDR 0xFF50FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_LPD_SLCR_SECURE_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_LPD_SLCR_SECURE_0_S_AXI_BASEADDR 0xFF510000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_LPD_SLCR_SECURE_0_S_AXI_HIGHADDR 0xFF54FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_LPD_XPPU_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_LPD_XPPU_0_S_AXI_BASEADDR 0xFF990000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_LPD_XPPU_0_S_AXI_HIGHADDR 0xFF99FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_OCM_CTRL */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_OCM_CTRL_S_AXI_BASEADDR 0xFF960000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_OCM_CTRL_S_AXI_HIGHADDR 0xFF96FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_OCM_RAM_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_OCM_RAM_0_S_AXI_BASEADDR 0xFFFC0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_OCM_RAM_0_S_AXI_HIGHADDR 0xFFFFFFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_OCM_XMPU_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_OCM_XMPU_0_S_AXI_BASEADDR 0xFF980000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_OCM_XMPU_0_S_AXI_HIGHADDR 0xFF98FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_AES */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_AES_S_AXI_BASEADDR 0xF11E0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_AES_S_AXI_HIGHADDR 0xF11EFFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_BBRAM_CTRL */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_BBRAM_CTRL_S_AXI_BASEADDR 0xF11F0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_BBRAM_CTRL_S_AXI_HIGHADDR 0xF11FFFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_EFUSE_CACHE */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_EFUSE_CACHE_S_AXI_BASEADDR 0xF1250000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_EFUSE_CACHE_S_AXI_HIGHADDR 0xF125FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_EFUSE_CTRL */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_EFUSE_CTRL_S_AXI_BASEADDR 0xF1240000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_EFUSE_CTRL_S_AXI_HIGHADDR 0xF124FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_GLOBAL_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_GLOBAL_0_S_AXI_BASEADDR 0xF1110000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_GLOBAL_0_S_AXI_HIGHADDR 0xF115FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_QSPI_OSPI_FLASH_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_QSPI_OSPI_FLASH_0_S_AXI_BASEADDR 0xC0000000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_QSPI_OSPI_FLASH_0_S_AXI_HIGHADDR 0xDFFFFFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_RAM */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_RAM_S_AXI_BASEADDR 0xF2000000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_RAM_S_AXI_HIGHADDR 0xF201FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_RAM_NPI */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_RAM_NPI_S_AXI_BASEADDR 0xF6000000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_RAM_NPI_S_AXI_HIGHADDR 0xF7FFFFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_RSA */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_RSA_S_AXI_BASEADDR 0xF1200000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_RSA_S_AXI_HIGHADDR 0xF120FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_SHA */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_SHA_S_AXI_BASEADDR 0xF1210000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_SHA_S_AXI_HIGHADDR 0xF121FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_XMPU_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_XMPU_0_S_AXI_BASEADDR 0xF12F0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_XMPU_0_S_AXI_HIGHADDR 0xF12FFFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_XPPU_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_XPPU_0_S_AXI_BASEADDR 0xF1310000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_XPPU_0_S_AXI_HIGHADDR 0xF131FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_XPPU_NPI_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_XPPU_NPI_0_S_AXI_BASEADDR 0xF1300000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_XPPU_NPI_0_S_AXI_HIGHADDR 0xF130FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PSM_GLOBAL_REG */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PSM_GLOBAL_REG_S_AXI_BASEADDR 0xFFC90000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PSM_GLOBAL_REG_S_AXI_HIGHADDR 0xFFC9EFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_R5_0_ATCM */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_R5_0_ATCM_S_AXI_BASEADDR 0x00000000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_R5_0_ATCM_S_AXI_HIGHADDR 0x0000FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_R5_0_BTCM */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_R5_0_BTCM_S_AXI_BASEADDR 0x00020000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_R5_0_BTCM_S_AXI_HIGHADDR 0x0002FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_R5_0_DATA_CACHE */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_R5_0_DATA_CACHE_S_AXI_BASEADDR 0xFFE50000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_R5_0_DATA_CACHE_S_AXI_HIGHADDR 0xFFE5FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_R5_0_INSTRUCTION_CACHE */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_R5_0_INSTRUCTION_CACHE_S_AXI_BASEADDR 0xFFE40000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_R5_0_INSTRUCTION_CACHE_S_AXI_HIGHADDR 0xFFE4FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_R5_1_DATA_CACHE */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_R5_1_DATA_CACHE_S_AXI_BASEADDR 0xFFED0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_R5_1_DATA_CACHE_S_AXI_HIGHADDR 0xFFEDFFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_R5_1_INSTRUCTION_CACHE */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_R5_1_INSTRUCTION_CACHE_S_AXI_BASEADDR 0xFFEC0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_R5_1_INSTRUCTION_CACHE_S_AXI_HIGHADDR 0xFFECFFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_R5_TCM_RAM_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_R5_TCM_RAM_0_S_AXI_BASEADDR 0x00000000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_R5_TCM_RAM_0_S_AXI_HIGHADDR 0x0003FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_RPU_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_RPU_0_S_AXI_BASEADDR 0xFF9A0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_RPU_0_S_AXI_HIGHADDR 0xFF9AFFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_SCNTR_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_SCNTR_0_S_AXI_BASEADDR 0xFF130000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_SCNTR_0_S_AXI_HIGHADDR 0xFF13FFFF


/* Peripheral Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_SCNTRS_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_SCNTRS_0_S_AXI_BASEADDR 0xFF140000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_SCNTRS_0_S_AXI_HIGHADDR 0xFF14FFFF


/* Peripheral Definitions for peripheral BLP_SHELL_UTILS_REMAP_0 */
#define XPAR_BLP_SHELL_UTILS_REMAP_0_BASEADDR 0x20108000000
#define XPAR_BLP_SHELL_UTILS_REMAP_0_HIGHADDR 0x2010FFFFFFF


/* Peripheral Definitions for peripheral BLP_SHELL_UTILS_REMAP_1 */
#define XPAR_BLP_SHELL_UTILS_REMAP_1_BASEADDR 0x20206000000
#define XPAR_BLP_SHELL_UTILS_REMAP_1_HIGHADDR 0x20206FFFFFF


/* Peripheral Definitions for peripheral ULP_AXI_DBG_HUB */
#define XPAR_ULP_AXI_DBG_HUB_BASEADDR 0x20205800000
#define XPAR_ULP_AXI_DBG_HUB_HIGHADDR 0x202059FFFFF


/******************************************************************/


/* Canonical Definitions for peripheral BLP_BLP_LOGIC_AXI_BLP_DBG_HUB */
#define XPAR_AXI_DBG_HUB_0_BASEADDR 0x20105000000
#define XPAR_AXI_DBG_HUB_0_HIGHADDR 0x201051FFFFF


/* Canonical Definitions for peripheral BLP_BLP_LOGIC_AXI_FIREWALL_USER */
#define XPAR_AXI_FIREWALL_0_BASEADDR 0x80001000
#define XPAR_AXI_FIREWALL_0_HIGHADDR 0x80001FFF


/* Canonical Definitions for peripheral BLP_BLP_LOGIC_PF0_BAR_LAYOUT */
#define XPAR_SHELL_UTILS_BAR_LAYOUT_TABLE_0_BASEADDR 0x20102001000
#define XPAR_SHELL_UTILS_BAR_LAYOUT_TABLE_0_HIGHADDR 0x20102001FFF


/* Canonical Definitions for peripheral BLP_BLP_LOGIC_PF1_BAR_LAYOUT */
#define XPAR_SHELL_UTILS_BAR_LAYOUT_TABLE_1_BASEADDR 0x20202001000
#define XPAR_SHELL_UTILS_BAR_LAYOUT_TABLE_1_HIGHADDR 0x20202001FFF


/* Canonical Definitions for peripheral BLP_BLP_LOGIC_SB_REMAP */
#define XPAR_SHELL_UTILS_VERSAL_REMAP_0_BASEADDR 0x20102030000
#define XPAR_SHELL_UTILS_VERSAL_REMAP_0_HIGHADDR 0x20102030FFF


/* Canonical Definitions for peripheral BLP_BLP_LOGIC_ULP_CLOCKING_FREQUENCY_COUNTERS_FREQUENCY_COUNTER_ACLK */
#define XPAR_SHELL_UTILS_FREQUENCY_COUNTER_0_BASEADDR 0x80036000
#define XPAR_SHELL_UTILS_FREQUENCY_COUNTER_0_HIGHADDR 0x80036FFF


/* Canonical Definitions for peripheral BLP_BLP_LOGIC_ULP_CLOCKING_FREQUENCY_COUNTERS_FREQUENCY_COUNTER_ACLK_KERNEL_00 */
#define XPAR_SHELL_UTILS_FREQUENCY_COUNTER_1_BASEADDR 0x80034000
#define XPAR_SHELL_UTILS_FREQUENCY_COUNTER_1_HIGHADDR 0x80034FFF


/* Canonical Definitions for peripheral BLP_BLP_LOGIC_ULP_CLOCKING_FREQUENCY_COUNTERS_FREQUENCY_COUNTER_ACLK_KERNEL_01 */
#define XPAR_SHELL_UTILS_FREQUENCY_COUNTER_2_BASEADDR 0x80035000
#define XPAR_SHELL_UTILS_FREQUENCY_COUNTER_2_HIGHADDR 0x80035FFF


/* Canonical Definitions for peripheral BLP_BLP_LOGIC_UUID_ROM */
#define XPAR_SHELL_UTILS_UUID_ROM_0_BASEADDR 0x20102002000
#define XPAR_SHELL_UTILS_UUID_ROM_0_HIGHADDR 0x20102002FFF


/* Canonical Definitions for peripheral BLP_BLP_LOGIC_XGQ_M2R */
#define XPAR_XRT_QUEUE_0_BASEADDR 0x80010000
#define XPAR_XRT_QUEUE_0_HIGHADDR 0x80010FFF


/* Canonical Definitions for peripheral BLP_BLP_LOGIC_XGQ_R2A */
#define XPAR_XRT_QUEUE_1_BASEADDR 0x80011000
#define XPAR_XRT_QUEUE_1_HIGHADDR 0x80011FFF


/* Canonical Definitions for peripheral BLP_BLP_LOGIC_XGQ_U2A_0 */
#define XPAR_XRT_QUEUE_2_BASEADDR 0x402010000
#define XPAR_XRT_QUEUE_2_HIGHADDR 0x402010FFF


/* Canonical Definitions for peripheral BLP_BLP_LOGIC_XGQ_U2A_1 */
#define XPAR_XRT_QUEUE_3_BASEADDR 0x402011000
#define XPAR_XRT_QUEUE_3_HIGHADDR 0x402011FFF


/* Canonical Definitions for peripheral BLP_BLP_LOGIC_XGQ_U2A_2 */
#define XPAR_XRT_QUEUE_4_BASEADDR 0x402012000
#define XPAR_XRT_QUEUE_4_HIGHADDR 0x402012FFF


/* Canonical Definitions for peripheral BLP_BLP_LOGIC_XGQ_U2A_3 */
#define XPAR_XRT_QUEUE_5_BASEADDR 0x402013000
#define XPAR_XRT_QUEUE_5_HIGHADDR 0x402013FFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_APU_0 */
#define XPAR_PSV_APU_0_S_AXI_BASEADDR 0xFD5C0000
#define XPAR_PSV_APU_0_S_AXI_HIGHADDR 0xFD5CFFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_CORESIGHT_FPD_STM */
#define XPAR_PSV_CORESIGHT_FPD_STM_0_S_AXI_BASEADDR 0xF0B70000
#define XPAR_PSV_CORESIGHT_FPD_STM_0_S_AXI_HIGHADDR 0xF0B7FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_CRF_0 */
#define XPAR_PSV_CRF_0_S_AXI_BASEADDR 0xFD1A0000
#define XPAR_PSV_CRF_0_S_AXI_HIGHADDR 0xFD2DFFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_CRL_0 */
#define XPAR_PSV_CRL_0_S_AXI_BASEADDR 0xFF5E0000
#define XPAR_PSV_CRL_0_S_AXI_HIGHADDR 0xFF8DFFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_CRP_0 */
#define XPAR_PSV_CRP_0_S_AXI_BASEADDR 0xF1260000
#define XPAR_PSV_CRP_0_S_AXI_HIGHADDR 0xF126FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_FPD_AFI_0 */
#define XPAR_PSV_FPD_AFI_0_S_AXI_BASEADDR 0xFD360000
#define XPAR_PSV_FPD_AFI_0_S_AXI_HIGHADDR 0xFD36FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_FPD_AFI_2 */
#define XPAR_PSV_FPD_AFI_1_S_AXI_BASEADDR 0xFD380000
#define XPAR_PSV_FPD_AFI_1_S_AXI_HIGHADDR 0xFD38FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_FPD_CCI_0 */
#define XPAR_PSV_FPD_CCI_0_S_AXI_BASEADDR 0xFD5E0000
#define XPAR_PSV_FPD_CCI_0_S_AXI_HIGHADDR 0xFD5EFFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_FPD_GPV_0 */
#define XPAR_PSV_FPD_GPV_0_S_AXI_BASEADDR 0xFD700000
#define XPAR_PSV_FPD_GPV_0_S_AXI_HIGHADDR 0xFD7FFFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_FPD_MAINCCI_0 */
#define XPAR_PSV_FPD_MAINCCI_0_S_AXI_BASEADDR 0xFD000000
#define XPAR_PSV_FPD_MAINCCI_0_S_AXI_HIGHADDR 0xFD0FFFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_FPD_SLAVE_XMPU_0 */
#define XPAR_PSV_FPD_SLAVE_XMPU_0_S_AXI_BASEADDR 0xFD390000
#define XPAR_PSV_FPD_SLAVE_XMPU_0_S_AXI_HIGHADDR 0xFD39FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_FPD_SLCR_0 */
#define XPAR_PSV_FPD_SLCR_0_S_AXI_BASEADDR 0xFD610000
#define XPAR_PSV_FPD_SLCR_0_S_AXI_HIGHADDR 0xFD61FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_FPD_SLCR_SECURE_0 */
#define XPAR_PSV_FPD_SLCR_SECURE_0_S_AXI_BASEADDR 0xFD690000
#define XPAR_PSV_FPD_SLCR_SECURE_0_S_AXI_HIGHADDR 0xFD69FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_FPD_SMMU_0 */
#define XPAR_PSV_FPD_SMMU_0_S_AXI_BASEADDR 0xFD5F0000
#define XPAR_PSV_FPD_SMMU_0_S_AXI_HIGHADDR 0xFD5FFFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_FPD_SMMUTCU_0 */
#define XPAR_PSV_FPD_SMMUTCU_0_S_AXI_BASEADDR 0xFD800000
#define XPAR_PSV_FPD_SMMUTCU_0_S_AXI_HIGHADDR 0xFDFFFFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_LPD_AFI_0 */
#define XPAR_PSV_LPD_AFI_0_S_AXI_BASEADDR 0xFF9B0000
#define XPAR_PSV_LPD_AFI_0_S_AXI_HIGHADDR 0xFF9BFFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_LPD_IOU_SECURE_SLCR_0 */
#define XPAR_PSV_LPD_IOU_SECURE_SLCR_0_S_AXI_BASEADDR 0xFF0A0000
#define XPAR_PSV_LPD_IOU_SECURE_SLCR_0_S_AXI_HIGHADDR 0xFF0AFFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_LPD_IOU_SLCR_0 */
#define XPAR_PSV_LPD_IOU_SLCR_0_S_AXI_BASEADDR 0xFF080000
#define XPAR_PSV_LPD_IOU_SLCR_0_S_AXI_HIGHADDR 0xFF09FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_LPD_SLCR_0 */
#define XPAR_PSV_LPD_SLCR_0_S_AXI_BASEADDR 0xFF410000
#define XPAR_PSV_LPD_SLCR_0_S_AXI_HIGHADDR 0xFF50FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_LPD_SLCR_SECURE_0 */
#define XPAR_PSV_LPD_SLCR_SECURE_0_S_AXI_BASEADDR 0xFF510000
#define XPAR_PSV_LPD_SLCR_SECURE_0_S_AXI_HIGHADDR 0xFF54FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_LPD_XPPU_0 */
#define XPAR_PSV_LPD_XPPU_0_S_AXI_BASEADDR 0xFF990000
#define XPAR_PSV_LPD_XPPU_0_S_AXI_HIGHADDR 0xFF99FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_OCM_CTRL */
#define XPAR_PSV_OCM_0_S_AXI_BASEADDR 0xFF960000
#define XPAR_PSV_OCM_0_S_AXI_HIGHADDR 0xFF96FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_OCM_RAM_0 */
#define XPAR_PSV_OCM_RAM_0_S_AXI_BASEADDR 0xFFFC0000
#define XPAR_PSV_OCM_RAM_0_S_AXI_HIGHADDR 0xFFFFFFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_OCM_XMPU_0 */
#define XPAR_PSV_OCM_XMPU_0_S_AXI_BASEADDR 0xFF980000
#define XPAR_PSV_OCM_XMPU_0_S_AXI_HIGHADDR 0xFF98FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_AES */
#define XPAR_PSV_PMC_AES_0_S_AXI_BASEADDR 0xF11E0000
#define XPAR_PSV_PMC_AES_0_S_AXI_HIGHADDR 0xF11EFFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_BBRAM_CTRL */
#define XPAR_PSV_PMC_BBRAM_CTRL_0_S_AXI_BASEADDR 0xF11F0000
#define XPAR_PSV_PMC_BBRAM_CTRL_0_S_AXI_HIGHADDR 0xF11FFFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_EFUSE_CACHE */
#define XPAR_PSV_PMC_EFUSE_CACHE_0_S_AXI_BASEADDR 0xF1250000
#define XPAR_PSV_PMC_EFUSE_CACHE_0_S_AXI_HIGHADDR 0xF125FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_EFUSE_CTRL */
#define XPAR_PSV_PMC_EFUSE_CTRL_0_S_AXI_BASEADDR 0xF1240000
#define XPAR_PSV_PMC_EFUSE_CTRL_0_S_AXI_HIGHADDR 0xF124FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_GLOBAL_0 */
#define XPAR_PSV_PMC_GLOBAL_0_S_AXI_BASEADDR 0xF1110000
#define XPAR_PSV_PMC_GLOBAL_0_S_AXI_HIGHADDR 0xF115FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_QSPI_OSPI_FLASH_0 */
#define XPAR_PSV_PMC_QSPI_OSPI_0_S_AXI_BASEADDR 0xC0000000
#define XPAR_PSV_PMC_QSPI_OSPI_0_S_AXI_HIGHADDR 0xDFFFFFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_RAM */
#define XPAR_PSV_PMC_RAM_0_S_AXI_BASEADDR 0xF2000000
#define XPAR_PSV_PMC_RAM_0_S_AXI_HIGHADDR 0xF201FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_RAM_NPI */
#define XPAR_PSV_PMC_RAM_NPI_0_S_AXI_BASEADDR 0xF6000000
#define XPAR_PSV_PMC_RAM_NPI_0_S_AXI_HIGHADDR 0xF7FFFFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_RSA */
#define XPAR_PSV_PMC_RSA_0_S_AXI_BASEADDR 0xF1200000
#define XPAR_PSV_PMC_RSA_0_S_AXI_HIGHADDR 0xF120FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_SHA */
#define XPAR_PSV_PMC_SHA_0_S_AXI_BASEADDR 0xF1210000
#define XPAR_PSV_PMC_SHA_0_S_AXI_HIGHADDR 0xF121FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_XMPU_0 */
#define XPAR_PSV_PMC_XMPU_0_S_AXI_BASEADDR 0xF12F0000
#define XPAR_PSV_PMC_XMPU_0_S_AXI_HIGHADDR 0xF12FFFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_XPPU_0 */
#define XPAR_PSV_PMC_XPPU_0_S_AXI_BASEADDR 0xF1310000
#define XPAR_PSV_PMC_XPPU_0_S_AXI_HIGHADDR 0xF131FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_XPPU_NPI_0 */
#define XPAR_PSV_PMC_XPPU_NPI_0_S_AXI_BASEADDR 0xF1300000
#define XPAR_PSV_PMC_XPPU_NPI_0_S_AXI_HIGHADDR 0xF130FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PSM_GLOBAL_REG */
#define XPAR_PSV_PSM_GLOBAL_REG_0_S_AXI_BASEADDR 0xFFC90000
#define XPAR_PSV_PSM_GLOBAL_REG_0_S_AXI_HIGHADDR 0xFFC9EFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_R5_0_ATCM */
#define XPAR_PSV_R5_TCM_0_S_AXI_BASEADDR 0x00000000
#define XPAR_PSV_R5_TCM_0_S_AXI_HIGHADDR 0x0000FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_R5_0_BTCM */
#define XPAR_PSV_R5_TCM_1_S_AXI_BASEADDR 0x00020000
#define XPAR_PSV_R5_TCM_1_S_AXI_HIGHADDR 0x0002FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_R5_0_DATA_CACHE */
#define XPAR_PSV_R5_0_DATA_CACHE_0_S_AXI_BASEADDR 0xFFE50000
#define XPAR_PSV_R5_0_DATA_CACHE_0_S_AXI_HIGHADDR 0xFFE5FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_R5_0_INSTRUCTION_CACHE */
#define XPAR_PSV_R5_0_INSTRUCTION_CACHE_0_S_AXI_BASEADDR 0xFFE40000
#define XPAR_PSV_R5_0_INSTRUCTION_CACHE_0_S_AXI_HIGHADDR 0xFFE4FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_R5_1_DATA_CACHE */
#define XPAR_PSV_R5_1_DATA_CACHE_0_S_AXI_BASEADDR 0xFFED0000
#define XPAR_PSV_R5_1_DATA_CACHE_0_S_AXI_HIGHADDR 0xFFEDFFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_R5_1_INSTRUCTION_CACHE */
#define XPAR_PSV_R5_1_INSTRUCTION_CACHE_0_S_AXI_BASEADDR 0xFFEC0000
#define XPAR_PSV_R5_1_INSTRUCTION_CACHE_0_S_AXI_HIGHADDR 0xFFECFFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_R5_TCM_RAM_0 */
#define XPAR_PSV_R5_TCM_2_S_AXI_BASEADDR 0x00000000
#define XPAR_PSV_R5_TCM_2_S_AXI_HIGHADDR 0x0003FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_RPU_0 */
#define XPAR_PSV_RPU_0_S_AXI_BASEADDR 0xFF9A0000
#define XPAR_PSV_RPU_0_S_AXI_HIGHADDR 0xFF9AFFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_SCNTR_0 */
#define XPAR_PSV_SCNTR_0_S_AXI_BASEADDR 0xFF130000
#define XPAR_PSV_SCNTR_0_S_AXI_HIGHADDR 0xFF13FFFF


/* Canonical Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_SCNTRS_0 */
#define XPAR_PSV_SCNTRS_0_S_AXI_BASEADDR 0xFF140000
#define XPAR_PSV_SCNTRS_0_S_AXI_HIGHADDR 0xFF14FFFF


/* Canonical Definitions for peripheral BLP_SHELL_UTILS_REMAP_0 */
#define XPAR_SHELL_UTILS_VERSAL_REMAP_1_BASEADDR 0x20108000000
#define XPAR_SHELL_UTILS_VERSAL_REMAP_1_HIGHADDR 0x2010FFFFFFF


/* Canonical Definitions for peripheral BLP_SHELL_UTILS_REMAP_1 */
#define XPAR_SHELL_UTILS_VERSAL_REMAP_2_BASEADDR 0x20206000000
#define XPAR_SHELL_UTILS_VERSAL_REMAP_2_HIGHADDR 0x20206FFFFFF


/* Canonical Definitions for peripheral ULP_AXI_DBG_HUB */
#define XPAR_AXI_DBG_HUB_1_BASEADDR 0x20205800000
#define XPAR_AXI_DBG_HUB_1_HIGHADDR 0x202059FFFFF


/******************************************************************/

/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 5

/* Definitions for peripheral BLP_BLP_LOGIC_BASE_CLOCKING_FORCE_RESET_GPIO */
#define XPAR_BLP_BLP_LOGIC_BASE_CLOCKING_FORCE_RESET_GPIO_BASEADDR 0x20102040000
#define XPAR_BLP_BLP_LOGIC_BASE_CLOCKING_FORCE_RESET_GPIO_HIGHADDR 0x20102040FFF
#define XPAR_BLP_BLP_LOGIC_BASE_CLOCKING_FORCE_RESET_GPIO_DEVICE_ID 0
#define XPAR_BLP_BLP_LOGIC_BASE_CLOCKING_FORCE_RESET_GPIO_INTERRUPT_PRESENT 0
#define XPAR_BLP_BLP_LOGIC_BASE_CLOCKING_FORCE_RESET_GPIO_IS_DUAL 1


/* Definitions for peripheral BLP_BLP_LOGIC_BASE_CLOCKING_PR_RESET_GPIO */
#define XPAR_BLP_BLP_LOGIC_BASE_CLOCKING_PR_RESET_GPIO_BASEADDR 0x80020000
#define XPAR_BLP_BLP_LOGIC_BASE_CLOCKING_PR_RESET_GPIO_HIGHADDR 0x80020FFF
#define XPAR_BLP_BLP_LOGIC_BASE_CLOCKING_PR_RESET_GPIO_DEVICE_ID 1
#define XPAR_BLP_BLP_LOGIC_BASE_CLOCKING_PR_RESET_GPIO_INTERRUPT_PRESENT 0
#define XPAR_BLP_BLP_LOGIC_BASE_CLOCKING_PR_RESET_GPIO_IS_DUAL 1


/* Definitions for peripheral BLP_BLP_LOGIC_ULP_CLOCKING_GAPPING_DEMAND_GPIO_GAPPING_DEMAND */
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_GAPPING_DEMAND_GPIO_GAPPING_DEMAND_BASEADDR 0x80030000
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_GAPPING_DEMAND_GPIO_GAPPING_DEMAND_HIGHADDR 0x80030FFF
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_GAPPING_DEMAND_GPIO_GAPPING_DEMAND_DEVICE_ID 2
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_GAPPING_DEMAND_GPIO_GAPPING_DEMAND_INTERRUPT_PRESENT 0
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_GAPPING_DEMAND_GPIO_GAPPING_DEMAND_IS_DUAL 1


/* Definitions for peripheral BLP_BLP_LOGIC_ULP_CLOCKING_UCS_CONTROL_STATUS_GPIO_UCS_CONTROL_STATUS */
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_UCS_CONTROL_STATUS_GPIO_UCS_CONTROL_STATUS_BASEADDR 0x80031000
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_UCS_CONTROL_STATUS_GPIO_UCS_CONTROL_STATUS_HIGHADDR 0x80031FFF
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_UCS_CONTROL_STATUS_GPIO_UCS_CONTROL_STATUS_DEVICE_ID 3
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_UCS_CONTROL_STATUS_GPIO_UCS_CONTROL_STATUS_INTERRUPT_PRESENT 0
#define XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_UCS_CONTROL_STATUS_GPIO_UCS_CONTROL_STATUS_IS_DUAL 1


/* Definitions for peripheral ULP_AXI_GPIO_NULL_USER */
#define XPAR_ULP_AXI_GPIO_NULL_USER_BASEADDR 0x20200000000
#define XPAR_ULP_AXI_GPIO_NULL_USER_HIGHADDR 0x20201FFFFFF
#define XPAR_ULP_AXI_GPIO_NULL_USER_DEVICE_ID 4
#define XPAR_ULP_AXI_GPIO_NULL_USER_INTERRUPT_PRESENT 0
#define XPAR_ULP_AXI_GPIO_NULL_USER_IS_DUAL 0


/******************************************************************/

/* Canonical definitions for peripheral BLP_BLP_LOGIC_BASE_CLOCKING_FORCE_RESET_GPIO */
#define XPAR_GPIO_0_BASEADDR 0x20102040000
#define XPAR_GPIO_0_HIGHADDR 0x20102040FFF
#define XPAR_GPIO_0_DEVICE_ID XPAR_BLP_BLP_LOGIC_BASE_CLOCKING_FORCE_RESET_GPIO_DEVICE_ID
#define XPAR_GPIO_0_INTERRUPT_PRESENT 0
#define XPAR_GPIO_0_IS_DUAL 1

/* Canonical definitions for peripheral BLP_BLP_LOGIC_BASE_CLOCKING_PR_RESET_GPIO */
#define XPAR_GPIO_1_BASEADDR 0x80020000
#define XPAR_GPIO_1_HIGHADDR 0x80020FFF
#define XPAR_GPIO_1_DEVICE_ID XPAR_BLP_BLP_LOGIC_BASE_CLOCKING_PR_RESET_GPIO_DEVICE_ID
#define XPAR_GPIO_1_INTERRUPT_PRESENT 0
#define XPAR_GPIO_1_IS_DUAL 1

/* Canonical definitions for peripheral BLP_BLP_LOGIC_ULP_CLOCKING_GAPPING_DEMAND_GPIO_GAPPING_DEMAND */
#define XPAR_GPIO_2_BASEADDR 0x80030000
#define XPAR_GPIO_2_HIGHADDR 0x80030FFF
#define XPAR_GPIO_2_DEVICE_ID XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_GAPPING_DEMAND_GPIO_GAPPING_DEMAND_DEVICE_ID
#define XPAR_GPIO_2_INTERRUPT_PRESENT 0
#define XPAR_GPIO_2_IS_DUAL 1

/* Canonical definitions for peripheral BLP_BLP_LOGIC_ULP_CLOCKING_UCS_CONTROL_STATUS_GPIO_UCS_CONTROL_STATUS */
#define XPAR_GPIO_3_BASEADDR 0x80031000
#define XPAR_GPIO_3_HIGHADDR 0x80031FFF
#define XPAR_GPIO_3_DEVICE_ID XPAR_BLP_BLP_LOGIC_ULP_CLOCKING_UCS_CONTROL_STATUS_GPIO_UCS_CONTROL_STATUS_DEVICE_ID
#define XPAR_GPIO_3_INTERRUPT_PRESENT 0
#define XPAR_GPIO_3_IS_DUAL 1

/* Canonical definitions for peripheral ULP_AXI_GPIO_NULL_USER */
#define XPAR_GPIO_4_BASEADDR 0x20200000000
#define XPAR_GPIO_4_HIGHADDR 0x20201FFFFFF
#define XPAR_GPIO_4_DEVICE_ID XPAR_ULP_AXI_GPIO_NULL_USER_DEVICE_ID
#define XPAR_GPIO_4_INTERRUPT_PRESENT 0
#define XPAR_GPIO_4_IS_DUAL 0


/******************************************************************/

/* Definitions for driver GPIOPS */
#define XPAR_XGPIOPS_NUM_INSTANCES 2

/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_GPIO_2 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_GPIO_2_DEVICE_ID 0
#define XPAR_BLP_CIPS_PSPMC_0_PSV_GPIO_2_BASEADDR 0xFF0B0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_GPIO_2_HIGHADDR 0xFF0BFFFF


/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_GPIO_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_GPIO_0_DEVICE_ID 1
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_GPIO_0_BASEADDR 0xF1020000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_GPIO_0_HIGHADDR 0xF102FFFF


/******************************************************************/

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_GPIO_2 */
#define XPAR_XGPIOPS_0_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_GPIO_2_DEVICE_ID
#define XPAR_XGPIOPS_0_BASEADDR 0xFF0B0000
#define XPAR_XGPIOPS_0_HIGHADDR 0xFF0BFFFF

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_GPIO_0 */
#define XPAR_XGPIOPS_1_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_GPIO_0_DEVICE_ID
#define XPAR_XGPIOPS_1_BASEADDR 0xF1020000
#define XPAR_XGPIOPS_1_HIGHADDR 0xF102FFFF


/******************************************************************/

/* Definitions for driver IICPS */
#define XPAR_XIICPS_NUM_INSTANCES 3

/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_I2C_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_I2C_0_DEVICE_ID 0
#define XPAR_BLP_CIPS_PSPMC_0_PSV_I2C_0_BASEADDR 0xFF020000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_I2C_0_HIGHADDR 0xFF02FFFF
#define XPAR_BLP_CIPS_PSPMC_0_PSV_I2C_0_I2C_CLK_FREQ_HZ 100000000


/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_I2C_1 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_I2C_1_DEVICE_ID 1
#define XPAR_BLP_CIPS_PSPMC_0_PSV_I2C_1_BASEADDR 0xFF030000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_I2C_1_HIGHADDR 0xFF03FFFF
#define XPAR_BLP_CIPS_PSPMC_0_PSV_I2C_1_I2C_CLK_FREQ_HZ 100000000


/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_I2C_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_I2C_0_DEVICE_ID 2
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_I2C_0_BASEADDR 0xF1000000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_I2C_0_HIGHADDR 0xF100FFFF
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_I2C_0_I2C_CLK_FREQ_HZ 100000000


/******************************************************************/

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_I2C_0 */
#define XPAR_XIICPS_0_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_I2C_0_DEVICE_ID
#define XPAR_XIICPS_0_BASEADDR 0xFF020000
#define XPAR_XIICPS_0_HIGHADDR 0xFF02FFFF
#define XPAR_XIICPS_0_I2C_CLK_FREQ_HZ 100000000

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_I2C_1 */
#define XPAR_XIICPS_1_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_I2C_1_DEVICE_ID
#define XPAR_XIICPS_1_BASEADDR 0xFF030000
#define XPAR_XIICPS_1_HIGHADDR 0xFF03FFFF
#define XPAR_XIICPS_1_I2C_CLK_FREQ_HZ 100000000

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_I2C_0 */
#define XPAR_XIICPS_2_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_I2C_0_DEVICE_ID
#define XPAR_XIICPS_2_BASEADDR 0xF1000000
#define XPAR_XIICPS_2_HIGHADDR 0xF100FFFF
#define XPAR_XIICPS_2_I2C_CLK_FREQ_HZ 100000000


/******************************************************************/

/* Definition for input Clock */
/* Definition for input Clock */
/* Definition for input Clock */
#define XPAR_INTC_MAX_NUM_INTR_INPUTS 32
#define XPAR_XINTC_HAS_IPR 1
#define XPAR_XINTC_HAS_SIE 1
#define XPAR_XINTC_HAS_CIE 1
#define XPAR_XINTC_HAS_IVR 1
/* Definitions for driver INTC */
#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31 */
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_DEVICE_ID 0
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BASEADDR 0x20202020000
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_HIGHADDR 0x20202020FFF
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_KIND_OF_INTR 0xFFFFFFFF
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_HAS_FAST 0
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_IVAR_RESET_VALUE 0x0000000000000010
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_NUM_INTR_INPUTS 32
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_NUM_SW_INTR 0
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_ADDR_WIDTH 32


/******************************************************************/

#define XPAR_INTC_SINGLE_BASEADDR 0x20202020000
#define XPAR_INTC_SINGLE_HIGHADDR 0x20202020FFF
#define XPAR_INTC_SINGLE_DEVICE_ID XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_DEVICE_ID
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_TYPE 0U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_MASK 0X000001U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_INTR 0U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_1_MASK 0X000002U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_1_INTR 1U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_2_MASK 0X000004U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_2_INTR 2U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_3_MASK 0X000008U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_3_INTR 3U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_4_MASK 0X000010U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_4_INTR 4U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_5_MASK 0X000020U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_5_INTR 5U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_6_MASK 0X000040U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_6_INTR 6U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_7_MASK 0X000080U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_7_INTR 7U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_8_MASK 0X000100U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_8_INTR 8U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_9_MASK 0X000200U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_9_INTR 9U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_10_MASK 0X000400U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_10_INTR 10U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_11_MASK 0X000800U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_11_INTR 11U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_12_MASK 0X001000U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_12_INTR 12U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_13_MASK 0X002000U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_13_INTR 13U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_14_MASK 0X004000U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_14_INTR 14U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_15_MASK 0X008000U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_15_INTR 15U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_LOW_PRIORITY_MASK 0X010000U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_LOW_PRIORITY_INTR 16U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_1_LOW_PRIORITY_MASK 0X020000U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_1_LOW_PRIORITY_INTR 17U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_2_LOW_PRIORITY_MASK 0X040000U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_2_LOW_PRIORITY_INTR 18U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_3_LOW_PRIORITY_MASK 0X080000U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_3_LOW_PRIORITY_INTR 19U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_4_LOW_PRIORITY_MASK 0X100000U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_4_LOW_PRIORITY_INTR 20U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_5_LOW_PRIORITY_MASK 0X200000U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_5_LOW_PRIORITY_INTR 21U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_6_LOW_PRIORITY_MASK 0X400000U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_6_LOW_PRIORITY_INTR 22U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_7_LOW_PRIORITY_MASK 0X800000U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_7_LOW_PRIORITY_INTR 23U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_8_LOW_PRIORITY_MASK 0X1000000U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_8_LOW_PRIORITY_INTR 24U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_9_LOW_PRIORITY_MASK 0X2000000U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_9_LOW_PRIORITY_INTR 25U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_10_LOW_PRIORITY_MASK 0X4000000U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_10_LOW_PRIORITY_INTR 26U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_11_LOW_PRIORITY_MASK 0X8000000U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_11_LOW_PRIORITY_INTR 27U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_12_LOW_PRIORITY_MASK 0X10000000U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_12_LOW_PRIORITY_INTR 28U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_13_LOW_PRIORITY_MASK 0X20000000U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_13_LOW_PRIORITY_INTR 29U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_14_LOW_PRIORITY_MASK 0X40000000U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_14_LOW_PRIORITY_INTR 30U
#define XPAR_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_15_LOW_PRIORITY_MASK 0X80000000U
#define XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BLP_DFX_DECOUPLING_IP_IRQ_KERNEL_00_Q_15_LOW_PRIORITY_INTR 31U

/******************************************************************/

/* Canonical definitions for peripheral BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31 */
#define XPAR_INTC_0_DEVICE_ID XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_DEVICE_ID
#define XPAR_INTC_0_BASEADDR 0x20202020000U
#define XPAR_INTC_0_HIGHADDR 0x20202020FFFU
#define XPAR_INTC_0_KIND_OF_INTR 0xFFFFFFFFU
#define XPAR_INTC_0_HAS_FAST 0U
#define XPAR_INTC_0_IVAR_RESET_VALUE 0x0000000000000010U
#define XPAR_INTC_0_NUM_INTR_INPUTS 32U
#define XPAR_INTC_0_NUM_SW_INTR 0U
#define XPAR_INTC_0_ADDR_WIDTH 32U
#define XPAR_INTC_0_INTC_TYPE 0U


/******************************************************************/

#define  XPAR_XIPIPSU_NUM_INSTANCES  2U

/* Parameter definitions for peripheral blp_cips_pspmc_0_psv_ipi_3 */
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_3_DEVICE_ID  0U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_3_S_AXI_BASEADDR  0xFF360000U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_3_BIT_MASK  0x00000020U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_3_BUFFER_INDEX  0x5U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_3_INT_ID  65U

/* Parameter definitions for peripheral blp_cips_pspmc_0_psv_ipi_4 */
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_4_DEVICE_ID  1U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_4_S_AXI_BASEADDR  0xFF370000U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_4_BIT_MASK  0x00000040U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_4_BUFFER_INDEX  0x6U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_4_INT_ID  66U

/* Canonical definitions for peripheral blp_cips_pspmc_0_psv_ipi_3 */
#define  XPAR_XIPIPSU_0_DEVICE_ID	XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_3_DEVICE_ID
#define  XPAR_XIPIPSU_0_BASE_ADDRESS	XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_3_S_AXI_BASEADDR
#define  XPAR_XIPIPSU_0_BIT_MASK	XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_3_BIT_MASK
#define  XPAR_XIPIPSU_0_BUFFER_INDEX	XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_3_BUFFER_INDEX
#define  XPAR_XIPIPSU_0_INT_ID	XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_3_INT_ID

/* Canonical definitions for peripheral blp_cips_pspmc_0_psv_ipi_4 */
#define  XPAR_XIPIPSU_1_DEVICE_ID	XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_4_DEVICE_ID
#define  XPAR_XIPIPSU_1_BASE_ADDRESS	XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_4_S_AXI_BASEADDR
#define  XPAR_XIPIPSU_1_BIT_MASK	XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_4_BIT_MASK
#define  XPAR_XIPIPSU_1_BUFFER_INDEX	XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_4_BUFFER_INDEX
#define  XPAR_XIPIPSU_1_INT_ID	XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_4_INT_ID

#define  XPAR_XIPIPSU_NUM_TARGETS  10U

#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_0_BIT_MASK  0x00000004U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_0_BUFFER_INDEX  0x2U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_1_BIT_MASK  0x00000008U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_1_BUFFER_INDEX  0x3U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_2_BIT_MASK  0x00000010U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_2_BUFFER_INDEX  0x4U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_3_BIT_MASK  0x00000020U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_3_BUFFER_INDEX  0x5U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_4_BIT_MASK  0x00000040U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_4_BUFFER_INDEX  0x6U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_5_BIT_MASK  0x00000080U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_5_BUFFER_INDEX  0x7U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_6_BIT_MASK  0x00000200U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_6_BUFFER_INDEX  0xFFFFU
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_PMC_BIT_MASK  0x00000002U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_PMC_BUFFER_INDEX  0x1U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_PMC_NOBUF_BIT_MASK  0x00000100U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_PMC_NOBUF_BUFFER_INDEX  0xFFFFU
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_PSM_BIT_MASK  0x00000001U
#define  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_PSM_BUFFER_INDEX  0x0U
/* Target List for referring to processor IPI Targets */

#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH0_MASK  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_0_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH0_INDEX  0U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH1_MASK  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_1_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH1_INDEX  1U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH2_MASK  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_2_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_0_CH2_INDEX  2U

#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH0_MASK  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_0_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH0_INDEX  0U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH1_MASK  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_1_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH1_INDEX  1U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH2_MASK  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_2_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXA72_1_CH2_INDEX  2U

#define  XPAR_XIPIPS_TARGET_PSV_CORTEXR5_0_CH0_MASK  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_3_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXR5_0_CH0_INDEX  3U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXR5_0_CH1_MASK  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_4_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXR5_0_CH1_INDEX  4U

#define  XPAR_XIPIPS_TARGET_PSV_CORTEXR5_1_CH0_MASK  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_5_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXR5_1_CH0_INDEX  5U
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXR5_1_CH1_MASK  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_6_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_CORTEXR5_1_CH1_INDEX  6U

#define  XPAR_XIPIPS_TARGET_PSV_PMC_0_CH0_MASK  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_PMC_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_PMC_0_CH0_INDEX  7U
#define  XPAR_XIPIPS_TARGET_PSV_PMC_0_CH1_MASK  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_PMC_NOBUF_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_PMC_0_CH1_INDEX  8U

#define  XPAR_XIPIPS_TARGET_PSV_PSM_0_CH0_MASK  XPAR_BLP_CIPS_PSPMC_0_PSV_IPI_PSM_BIT_MASK
#define  XPAR_XIPIPS_TARGET_PSV_PSM_0_CH0_INDEX  9U


/* Definitions for peripheral BLP_BLP_LOGIC_PF_MAILBOX IF 0 */
#define XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_0_DEVICE_ID 0U
#define XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_0_BASEADDR 0x20102000000U
#define XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_0_USE_FSL 0U
#define XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_0_SEND_FSL 0U
#define XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_0_RECV_FSL 0U

/* Definition for TestApp ID */
#define XPAR_BLP_BLP_LOGIC_PF_MAILBOX_TESTAPP_ID 0U

/* Definitions for peripheral BLP_BLP_LOGIC_PF_MAILBOX IF 1 */
#define XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_1_DEVICE_ID 1U
#define XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_1_BASEADDR 0x20202000000U
#define XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_1_USE_FSL 0U
#define XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_1_SEND_FSL 0U
#define XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_1_RECV_FSL 0U

/* Definitions for driver MAILBOX */
#define XPAR_XMBOX_NUM_INSTANCES 2U

/******************************************************************/


/* Canonical definitions for peripheral BLP_BLP_LOGIC_PF_MAILBOX IF 0 */
#define XPAR_MBOX_0_DEVICE_ID XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_0_DEVICE_ID
#define XPAR_MBOX_0_BASEADDR 0x20102000000U
#define XPAR_MBOX_0_HIGHADDR 0x20102000FFFU
#define XPAR_MBOX_0_USE_FSL XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_0_USE_FSL
#define XPAR_MBOX_0_SEND_FSL XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_0_SEND_FSL
#define XPAR_MBOX_0_RECV_FSL XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_0_RECV_FSL


/* Canonical definitions for peripheral BLP_BLP_LOGIC_PF_MAILBOX IF 1 */
#define XPAR_MBOX_1_DEVICE_ID XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_1_DEVICE_ID
#define XPAR_MBOX_1_BASEADDR 0x20202000000U
#define XPAR_MBOX_1_HIGHADDR 0x20202000FFFU
#define XPAR_MBOX_1_USE_FSL XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_1_USE_FSL
#define XPAR_MBOX_1_SEND_FSL XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_1_SEND_FSL
#define XPAR_MBOX_1_RECV_FSL XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_1_RECV_FSL


/******************************************************************/

/* Definitions for driver OSPIPSV */
#define XPAR_XOSPIPSV_NUM_INSTANCES 1

/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_OSPI_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_OSPI_0_DEVICE_ID 0
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_OSPI_0_BASEADDR 0xF1010000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_OSPI_0_HIGHADDR 0xF101FFFF
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_OSPI_0_OSPI_CLK_FREQ_HZ 100000000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_OSPI_0_OSPI_MODE 0


/******************************************************************/

#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_OSPI_0_IS_CACHE_COHERENT 0
/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_OSPI_0 */
#define XPAR_XOSPIPSV_0_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_OSPI_0_DEVICE_ID
#define XPAR_XOSPIPSV_0_BASEADDR 0xF1010000
#define XPAR_XOSPIPSV_0_HIGHADDR 0xF101FFFF
#define XPAR_XOSPIPSV_0_OSPI_CLK_FREQ_HZ 100000000
#define XPAR_XOSPIPSV_0_IS_CACHE_COHERENT 0
#define XPAR_XOSPIPSV_0_OSPI_MODE 0


/******************************************************************/

/* Definitions for driver PMONPSV */
#define XPAR_XPMONPSV_NUM_INSTANCES 2

/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_CORESIGHT_FPD_ATM */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_CORESIGHT_FPD_ATM_DEVICE_ID 0
#define XPAR_BLP_CIPS_PSPMC_0_PSV_CORESIGHT_FPD_ATM_S_AXI_BASEADDR 0xF0B80000


/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_CORESIGHT_LPD_ATM */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_CORESIGHT_LPD_ATM_DEVICE_ID 1
#define XPAR_BLP_CIPS_PSPMC_0_PSV_CORESIGHT_LPD_ATM_S_AXI_BASEADDR 0xF0980000


/******************************************************************/

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_CORESIGHT_FPD_ATM */
#define XPAR_XPMONPSV_0_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_CORESIGHT_FPD_ATM_DEVICE_ID
#define XPAR_XPMONPSV_0_S_AXI_BASEADDR 0xF0B80000

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_CORESIGHT_LPD_ATM */
#define XPAR_XPMONPSV_1_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_CORESIGHT_LPD_ATM_DEVICE_ID
#define XPAR_XPMONPSV_1_S_AXI_BASEADDR 0xF0980000


/******************************************************************/

/* Definitions for driver RTCPSU */
#define XPAR_XRTCPSU_NUM_INSTANCES 1

/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_RTC_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_RTC_0_DEVICE_ID 0
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_RTC_0_BASEADDR 0xF12A0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_RTC_0_HIGHADDR 0xF12AFFFF


/******************************************************************/

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_RTC_0 */
#define XPAR_XRTCPSU_0_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_RTC_0_DEVICE_ID
#define XPAR_XRTCPSU_0_BASEADDR 0xF12A0000
#define XPAR_XRTCPSU_0_HIGHADDR 0xF12AFFFF


/******************************************************************/

/* Definitions for Fabric interrupts connected to blp_cips_pspmc_0_psv_rcpu_gic */
#define XPAR_FABRIC_BLP_BLP_LOGIC_XGQ_M2R_IRQ_SQ_INTR 116U
#define XPAR_FABRIC_BLP_BLP_LOGIC_XGQ_R2A_IRQ_CQ_INTR 117U
#define XPAR_FABRIC_BLP_BLP_LOGIC_AXI_UART_APU_INTERRUPT_INTR 126U
#define XPAR_FABRIC_BLP_BLP_LOGIC_XGQ_U2A_0_IRQ_SQ_INTR 127U
#define XPAR_FABRIC_BLP_BLP_LOGIC_XGQ_U2A_1_IRQ_SQ_INTR 128U
#define XPAR_FABRIC_BLP_BLP_LOGIC_XGQ_U2A_2_IRQ_SQ_INTR 129U
#define XPAR_FABRIC_BLP_BLP_LOGIC_XGQ_U2A_3_IRQ_SQ_INTR 130U
#define XPAR_FABRIC_BLP_BLP_LOGIC_AXI_UART_RPU_INTERRUPT_INTR 119U
#define XPAR_FABRIC_BLP_BLP_LOGIC_XGQ_R2A_IRQ_SQ_INTR 124U
#define XPAR_FABRIC_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_IRQ_INTR 125U

/******************************************************************/

/* Canonical definitions for Fabric interrupts connected to blp_cips_pspmc_0_psv_rcpu_gic */
#define XPAR_FABRIC_UARTLITE_0_VEC_ID XPAR_FABRIC_BLP_BLP_LOGIC_AXI_UART_APU_INTERRUPT_INTR
#define XPAR_FABRIC_UARTLITE_3_VEC_ID XPAR_FABRIC_BLP_BLP_LOGIC_AXI_UART_RPU_INTERRUPT_INTR
#define XPAR_FABRIC_INTC_0_VEC_ID XPAR_FABRIC_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_IRQ_INTR

/******************************************************************/

/* Definitions for driver SCUGIC */
#define XPAR_XSCUGIC_NUM_INSTANCES 1U

/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_RCPU_GIC */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_RCPU_GIC_DEVICE_ID 0U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_RCPU_GIC_BASEADDR 0xF9001000U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_RCPU_GIC_HIGHADDR 0xF9001FFFU
#define XPAR_BLP_CIPS_PSPMC_0_PSV_RCPU_GIC_DIST_BASEADDR 0xF9000000U


/******************************************************************/

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_RCPU_GIC */
#define XPAR_SCUGIC_0_DEVICE_ID 0U
#define XPAR_SCUGIC_0_CPU_BASEADDR 0xF9001000U
#define XPAR_SCUGIC_0_CPU_HIGHADDR 0xF9001FFFU
#define XPAR_SCUGIC_0_DIST_BASEADDR 0xF9000000U


/******************************************************************/

#define XPAR_XSYSMONPSV_NUM_INSTANCES 1

/* Definitions for peripheral  */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_SYSMON_0_S_AXI_BASEADDR 0xF1270000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_SYSMON_0_S_AXI_HIGHADDR 0xF129FFFF
#define XPAR_PMC_SYSMON_0_VCCINT	0


/******************************************************************/

/* Canonical definitions for peripheral  */
#define XPAR_XSYSMONPSV_0_S_AXI_BASEADDR 0xF1270000
#define XPAR_XSYSMONPSV_0_S_AXI_HIGHADDR 0xF129FFFF

#define XPAR_XSYSMONPSV_0_VCCINT	0

/******************************************************************/

/* Xilinx Sysmon Device Name */

/******************************************************************/

/* Definitions for driver TRNGPSV */
#define XPAR_XTRNGPSV_NUM_INSTANCES 1

/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_TRNG */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_TRNG_DEVICE_ID 0
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_TRNG_BASEADDR 0xF1230000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_TRNG_HIGHADDR 0xF123FFFF


/******************************************************************/

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_TRNG */
#define XPAR_XTRNGPSV_0_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_TRNG_DEVICE_ID
#define XPAR_XTRNGPSV_0_BASEADDR 0xF1230000
#define XPAR_XTRNGPSV_0_HIGHADDR 0xF123FFFF


/******************************************************************/

/* Definitions for driver TTCPS */
#define XPAR_XTTCPS_NUM_INSTANCES 12U

/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_TTC_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_0_DEVICE_ID 0U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_0_BASEADDR 0XFF0E0000U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_0_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_0_TTC_CLK_CLKSRC 0U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_1_DEVICE_ID 1U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_1_BASEADDR 0XFF0E0004U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_1_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_1_TTC_CLK_CLKSRC 0U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_2_DEVICE_ID 2U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_2_BASEADDR 0XFF0E0008U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_2_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_2_TTC_CLK_CLKSRC 0U


/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_TTC_1 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_3_DEVICE_ID 3U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_3_BASEADDR 0XFF0F0000U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_3_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_3_TTC_CLK_CLKSRC 0U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_4_DEVICE_ID 4U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_4_BASEADDR 0XFF0F0004U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_4_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_4_TTC_CLK_CLKSRC 0U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_5_DEVICE_ID 5U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_5_BASEADDR 0XFF0F0008U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_5_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_5_TTC_CLK_CLKSRC 0U


/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_TTC_2 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_6_DEVICE_ID 6U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_6_BASEADDR 0XFF100000U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_6_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_6_TTC_CLK_CLKSRC 0U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_7_DEVICE_ID 7U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_7_BASEADDR 0XFF100004U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_7_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_7_TTC_CLK_CLKSRC 0U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_8_DEVICE_ID 8U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_8_BASEADDR 0XFF100008U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_8_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_8_TTC_CLK_CLKSRC 0U


/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_TTC_3 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_9_DEVICE_ID 9U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_9_BASEADDR 0XFF110000U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_9_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_9_TTC_CLK_CLKSRC 0U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_10_DEVICE_ID 10U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_10_BASEADDR 0XFF110004U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_10_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_10_TTC_CLK_CLKSRC 0U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_11_DEVICE_ID 11U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_11_BASEADDR 0XFF110008U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_11_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_11_TTC_CLK_CLKSRC 0U


/******************************************************************/

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_TTC_0 */
#define XPAR_XTTCPS_0_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_0_DEVICE_ID
#define XPAR_XTTCPS_0_BASEADDR 0xFF0E0000U
#define XPAR_XTTCPS_0_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_XTTCPS_0_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_1_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_1_DEVICE_ID
#define XPAR_XTTCPS_1_BASEADDR 0xFF0E0004U
#define XPAR_XTTCPS_1_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_XTTCPS_1_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_2_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_2_DEVICE_ID
#define XPAR_XTTCPS_2_BASEADDR 0xFF0E0008U
#define XPAR_XTTCPS_2_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_XTTCPS_2_TTC_CLK_CLKSRC 0U

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_TTC_1 */
#define XPAR_XTTCPS_3_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_3_DEVICE_ID
#define XPAR_XTTCPS_3_BASEADDR 0xFF0F0000U
#define XPAR_XTTCPS_3_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_XTTCPS_3_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_4_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_4_DEVICE_ID
#define XPAR_XTTCPS_4_BASEADDR 0xFF0F0004U
#define XPAR_XTTCPS_4_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_XTTCPS_4_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_5_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_5_DEVICE_ID
#define XPAR_XTTCPS_5_BASEADDR 0xFF0F0008U
#define XPAR_XTTCPS_5_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_XTTCPS_5_TTC_CLK_CLKSRC 0U

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_TTC_2 */
#define XPAR_XTTCPS_6_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_6_DEVICE_ID
#define XPAR_XTTCPS_6_BASEADDR 0xFF100000U
#define XPAR_XTTCPS_6_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_XTTCPS_6_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_7_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_7_DEVICE_ID
#define XPAR_XTTCPS_7_BASEADDR 0xFF100004U
#define XPAR_XTTCPS_7_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_XTTCPS_7_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_8_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_8_DEVICE_ID
#define XPAR_XTTCPS_8_BASEADDR 0xFF100008U
#define XPAR_XTTCPS_8_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_XTTCPS_8_TTC_CLK_CLKSRC 0U

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_TTC_3 */
#define XPAR_XTTCPS_9_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_9_DEVICE_ID
#define XPAR_XTTCPS_9_BASEADDR 0xFF110000U
#define XPAR_XTTCPS_9_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_XTTCPS_9_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_10_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_10_DEVICE_ID
#define XPAR_XTTCPS_10_BASEADDR 0xFF110004U
#define XPAR_XTTCPS_10_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_XTTCPS_10_TTC_CLK_CLKSRC 0U

#define XPAR_XTTCPS_11_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_TTC_11_DEVICE_ID
#define XPAR_XTTCPS_11_BASEADDR 0xFF110008U
#define XPAR_XTTCPS_11_TTC_CLK_FREQ_HZ 150000000U
#define XPAR_XTTCPS_11_TTC_CLK_CLKSRC 0U


/******************************************************************/

/* Definitions for driver UARTLITE */
#define XPAR_XUARTLITE_NUM_INSTANCES 5U

/* Definitions for peripheral BLP_BLP_LOGIC_AXI_UART_APU */
#define XPAR_BLP_BLP_LOGIC_AXI_UART_APU_DEVICE_ID 0U
#define XPAR_BLP_BLP_LOGIC_AXI_UART_APU_BASEADDR 0x402020000U
#define XPAR_BLP_BLP_LOGIC_AXI_UART_APU_HIGHADDR 0x402020FFFU
#define XPAR_BLP_BLP_LOGIC_AXI_UART_APU_BAUDRATE 230400U
#define XPAR_BLP_BLP_LOGIC_AXI_UART_APU_USE_PARITY 0U
#define XPAR_BLP_BLP_LOGIC_AXI_UART_APU_ODD_PARITY 0U
#define XPAR_BLP_BLP_LOGIC_AXI_UART_APU_DATA_BITS 8U

/* Canonical definitions for peripheral BLP_BLP_LOGIC_AXI_UART_APU */
#define XPAR_UARTLITE_0_DEVICE_ID 0U
#define XPAR_UARTLITE_0_BASEADDR 0x402020000U
#define XPAR_UARTLITE_0_HIGHADDR 0x402020FFFU
#define XPAR_UARTLITE_0_BAUDRATE 230400U
#define XPAR_UARTLITE_0_USE_PARITY 0U
#define XPAR_UARTLITE_0_ODD_PARITY 0U
#define XPAR_UARTLITE_0_DATA_BITS 8U



/* Definitions for peripheral BLP_BLP_LOGIC_AXI_UART_MGMT_APU */
#define XPAR_BLP_BLP_LOGIC_AXI_UART_MGMT_APU_DEVICE_ID 1U
#define XPAR_BLP_BLP_LOGIC_AXI_UART_MGMT_APU_BASEADDR 0x20102021000U
#define XPAR_BLP_BLP_LOGIC_AXI_UART_MGMT_APU_HIGHADDR 0x20102021FFFU
#define XPAR_BLP_BLP_LOGIC_AXI_UART_MGMT_APU_BAUDRATE 230400U
#define XPAR_BLP_BLP_LOGIC_AXI_UART_MGMT_APU_USE_PARITY 0U
#define XPAR_BLP_BLP_LOGIC_AXI_UART_MGMT_APU_ODD_PARITY 0U
#define XPAR_BLP_BLP_LOGIC_AXI_UART_MGMT_APU_DATA_BITS 8U

/* Canonical definitions for peripheral BLP_BLP_LOGIC_AXI_UART_MGMT_APU */
#define XPAR_UARTLITE_1_DEVICE_ID 1U
#define XPAR_UARTLITE_1_BASEADDR 0x20102021000U
#define XPAR_UARTLITE_1_HIGHADDR 0x20102021FFFU
#define XPAR_UARTLITE_1_BAUDRATE 230400U
#define XPAR_UARTLITE_1_USE_PARITY 0U
#define XPAR_UARTLITE_1_ODD_PARITY 0U
#define XPAR_UARTLITE_1_DATA_BITS 8U



/* Definitions for peripheral BLP_BLP_LOGIC_AXI_UART_MGMT_RPU */
#define XPAR_BLP_BLP_LOGIC_AXI_UART_MGMT_RPU_DEVICE_ID 2U
#define XPAR_BLP_BLP_LOGIC_AXI_UART_MGMT_RPU_BASEADDR 0x20102020000U
#define XPAR_BLP_BLP_LOGIC_AXI_UART_MGMT_RPU_HIGHADDR 0x20102020FFFU
#define XPAR_BLP_BLP_LOGIC_AXI_UART_MGMT_RPU_BAUDRATE 230400U
#define XPAR_BLP_BLP_LOGIC_AXI_UART_MGMT_RPU_USE_PARITY 0U
#define XPAR_BLP_BLP_LOGIC_AXI_UART_MGMT_RPU_ODD_PARITY 0U
#define XPAR_BLP_BLP_LOGIC_AXI_UART_MGMT_RPU_DATA_BITS 8U

/* Canonical definitions for peripheral BLP_BLP_LOGIC_AXI_UART_MGMT_RPU */
#define XPAR_UARTLITE_2_DEVICE_ID 2U
#define XPAR_UARTLITE_2_BASEADDR 0x20102020000U
#define XPAR_UARTLITE_2_HIGHADDR 0x20102020FFFU
#define XPAR_UARTLITE_2_BAUDRATE 230400U
#define XPAR_UARTLITE_2_USE_PARITY 0U
#define XPAR_UARTLITE_2_ODD_PARITY 0U
#define XPAR_UARTLITE_2_DATA_BITS 8U



/* Definitions for peripheral BLP_BLP_LOGIC_AXI_UART_RPU */
#define XPAR_BLP_BLP_LOGIC_AXI_UART_RPU_DEVICE_ID 3U
#define XPAR_BLP_BLP_LOGIC_AXI_UART_RPU_BASEADDR 0x80021000U
#define XPAR_BLP_BLP_LOGIC_AXI_UART_RPU_HIGHADDR 0x80021FFFU
#define XPAR_BLP_BLP_LOGIC_AXI_UART_RPU_BAUDRATE 230400U
#define XPAR_BLP_BLP_LOGIC_AXI_UART_RPU_USE_PARITY 0U
#define XPAR_BLP_BLP_LOGIC_AXI_UART_RPU_ODD_PARITY 0U
#define XPAR_BLP_BLP_LOGIC_AXI_UART_RPU_DATA_BITS 8U

/* Canonical definitions for peripheral BLP_BLP_LOGIC_AXI_UART_RPU */
#define XPAR_UARTLITE_3_DEVICE_ID 3U
#define XPAR_UARTLITE_3_BASEADDR 0x80021000U
#define XPAR_UARTLITE_3_HIGHADDR 0x80021FFFU
#define XPAR_UARTLITE_3_BAUDRATE 230400U
#define XPAR_UARTLITE_3_USE_PARITY 0U
#define XPAR_UARTLITE_3_ODD_PARITY 0U
#define XPAR_UARTLITE_3_DATA_BITS 8U



/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_PPU1_MDM_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_PPU1_MDM_0_DEVICE_ID 4U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_PPU1_MDM_0_BASEADDR 0xF0310000U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_PPU1_MDM_0_HIGHADDR 0xF0317FFFU
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_PPU1_MDM_0_BAUDRATE 0U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_PPU1_MDM_0_USE_PARITY 0U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_PPU1_MDM_0_ODD_PARITY 0U
#define XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_PPU1_MDM_0_DATA_BITS 0U

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_PMC_PPU1_MDM_0 */
#define XPAR_UARTLITE_4_DEVICE_ID 4U
#define XPAR_UARTLITE_4_BASEADDR 0xF0310000U
#define XPAR_UARTLITE_4_HIGHADDR 0xF0317FFFU
#define XPAR_UARTLITE_4_BAUDRATE 0U
#define XPAR_UARTLITE_4_USE_PARITY 0U
#define XPAR_UARTLITE_4_ODD_PARITY 0U
#define XPAR_UARTLITE_4_DATA_BITS 0U


/******************************************************************/
/* Definitions for driver UARTPSV */
#define XPAR_XUARTPSV_NUM_INSTANCES 2

/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_SBSAUART_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_0_DEVICE_ID 0
#define XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_0_BASEADDR 0xFF000000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_0_HIGHADDR 0xFF00FFFF
#define XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_0_UART_CLK_FREQ_HZ 100000000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_0_HAS_MODEM 0
#define XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_0_BAUDRATE 115200


/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_SBSAUART_1 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_1_DEVICE_ID 1
#define XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_1_BASEADDR 0xFF010000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_1_HIGHADDR 0xFF01FFFF
#define XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_1_UART_CLK_FREQ_HZ 100000000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_1_HAS_MODEM 0
#define XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_1_BAUDRATE 115200


/******************************************************************/

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_SBSAUART_0 */
#define XPAR_XUARTPSV_0_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_0_DEVICE_ID
#define XPAR_XUARTPSV_0_BASEADDR 0xFF000000
#define XPAR_XUARTPSV_0_HIGHADDR 0xFF00FFFF
#define XPAR_XUARTPSV_0_UART_CLK_FREQ_HZ 100000000
#define XPAR_XUARTPSV_0_HAS_MODEM 0
#define XPAR_XUARTPSV_0_BAUDRATE 115200

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_SBSAUART_1 */
#define XPAR_XUARTPSV_1_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_1_DEVICE_ID
#define XPAR_XUARTPSV_1_BASEADDR 0xFF010000
#define XPAR_XUARTPSV_1_HIGHADDR 0xFF01FFFF
#define XPAR_XUARTPSV_1_UART_CLK_FREQ_HZ 100000000
#define XPAR_XUARTPSV_1_HAS_MODEM 0
#define XPAR_XUARTPSV_1_BAUDRATE 115200


/******************************************************************/

/* Definitions for driver ZDMA */
#define XPAR_XZDMA_NUM_INSTANCES 8

/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_ADMA_0 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_0_DEVICE_ID 0
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_0_BASEADDR 0xFFA80000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_0_DMA_MODE 1
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_0_HIGHADDR 0xFFA8FFFF
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_0_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_ADMA_1 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_1_DEVICE_ID 1
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_1_BASEADDR 0xFFA90000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_1_DMA_MODE 1
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_1_HIGHADDR 0xFFA9FFFF
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_1_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_ADMA_2 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_2_DEVICE_ID 2
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_2_BASEADDR 0xFFAA0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_2_DMA_MODE 1
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_2_HIGHADDR 0xFFAAFFFF
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_2_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_ADMA_3 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_3_DEVICE_ID 3
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_3_BASEADDR 0xFFAB0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_3_DMA_MODE 1
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_3_HIGHADDR 0xFFABFFFF
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_3_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_ADMA_4 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_4_DEVICE_ID 4
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_4_BASEADDR 0xFFAC0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_4_DMA_MODE 1
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_4_HIGHADDR 0xFFACFFFF
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_4_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_ADMA_5 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_5_DEVICE_ID 5
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_5_BASEADDR 0xFFAD0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_5_DMA_MODE 1
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_5_HIGHADDR 0xFFADFFFF
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_5_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_ADMA_6 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_6_DEVICE_ID 6
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_6_BASEADDR 0xFFAE0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_6_DMA_MODE 1
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_6_HIGHADDR 0xFFAEFFFF
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_6_ZDMA_CLK_FREQ_HZ 0


/* Definitions for peripheral BLP_CIPS_PSPMC_0_PSV_ADMA_7 */
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_7_DEVICE_ID 7
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_7_BASEADDR 0xFFAF0000
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_7_DMA_MODE 1
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_7_HIGHADDR 0xFFAFFFFF
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_7_ZDMA_CLK_FREQ_HZ 0


/******************************************************************/

#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_0_IS_CACHE_COHERENT 0
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_1_IS_CACHE_COHERENT 0
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_2_IS_CACHE_COHERENT 0
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_3_IS_CACHE_COHERENT 0
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_4_IS_CACHE_COHERENT 0
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_5_IS_CACHE_COHERENT 0
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_6_IS_CACHE_COHERENT 0
#define XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_7_IS_CACHE_COHERENT 0
/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_ADMA_0 */
#define XPAR_XZDMA_0_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_0_DEVICE_ID
#define XPAR_XZDMA_0_BASEADDR 0xFFA80000
#define XPAR_XZDMA_0_DMA_MODE 1
#define XPAR_XZDMA_0_HIGHADDR 0xFFA8FFFF
#define XPAR_XZDMA_0_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_ADMA_1 */
#define XPAR_XZDMA_1_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_1_DEVICE_ID
#define XPAR_XZDMA_1_BASEADDR 0xFFA90000
#define XPAR_XZDMA_1_DMA_MODE 1
#define XPAR_XZDMA_1_HIGHADDR 0xFFA9FFFF
#define XPAR_XZDMA_1_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_ADMA_2 */
#define XPAR_XZDMA_2_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_2_DEVICE_ID
#define XPAR_XZDMA_2_BASEADDR 0xFFAA0000
#define XPAR_XZDMA_2_DMA_MODE 1
#define XPAR_XZDMA_2_HIGHADDR 0xFFAAFFFF
#define XPAR_XZDMA_2_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_ADMA_3 */
#define XPAR_XZDMA_3_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_3_DEVICE_ID
#define XPAR_XZDMA_3_BASEADDR 0xFFAB0000
#define XPAR_XZDMA_3_DMA_MODE 1
#define XPAR_XZDMA_3_HIGHADDR 0xFFABFFFF
#define XPAR_XZDMA_3_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_ADMA_4 */
#define XPAR_XZDMA_4_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_4_DEVICE_ID
#define XPAR_XZDMA_4_BASEADDR 0xFFAC0000
#define XPAR_XZDMA_4_DMA_MODE 1
#define XPAR_XZDMA_4_HIGHADDR 0xFFACFFFF
#define XPAR_XZDMA_4_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_ADMA_5 */
#define XPAR_XZDMA_5_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_5_DEVICE_ID
#define XPAR_XZDMA_5_BASEADDR 0xFFAD0000
#define XPAR_XZDMA_5_DMA_MODE 1
#define XPAR_XZDMA_5_HIGHADDR 0xFFADFFFF
#define XPAR_XZDMA_5_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_ADMA_6 */
#define XPAR_XZDMA_6_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_6_DEVICE_ID
#define XPAR_XZDMA_6_BASEADDR 0xFFAE0000
#define XPAR_XZDMA_6_DMA_MODE 1
#define XPAR_XZDMA_6_HIGHADDR 0xFFAEFFFF
#define XPAR_XZDMA_6_ZDMA_CLK_FREQ_HZ 0

/* Canonical definitions for peripheral BLP_CIPS_PSPMC_0_PSV_ADMA_7 */
#define XPAR_XZDMA_7_DEVICE_ID XPAR_BLP_CIPS_PSPMC_0_PSV_ADMA_7_DEVICE_ID
#define XPAR_XZDMA_7_BASEADDR 0xFFAF0000
#define XPAR_XZDMA_7_DMA_MODE 1
#define XPAR_XZDMA_7_HIGHADDR 0xFFAFFFFF
#define XPAR_XZDMA_7_ZDMA_CLK_FREQ_HZ 0


/******************************************************************/

#endif  /* end of protection macro */
