/******************************************************************************
* Copyright (C) 2024 Advanced Micro Devices, Inc.    All rights reserved.
* SPDX-License-Identifier: MIT
*******************************************************************************/

/*
 * Do not modify, this is automatically generated by build.sh with github versions.
 * including:
 * 	VMR_GIT_HASH
 * 	VMR_GIT_BRANCH
 * 	VMR_GIT_BUILD_DATE
 */
