
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xpmonpsv.h"

/*
* The configuration table for devices
*/

XPmonPsv_Config XPmonPsv_ConfigTable[XPAR_XPMONPSV_NUM_INSTANCES] =
{
	{
		XPAR_BLP_CIPS_PSPMC_0_PSV_CORESIGHT_FPD_ATM_DEVICE_ID,
		XPAR_BLP_CIPS_PSPMC_0_PSV_CORESIGHT_FPD_ATM_S_AXI_BASEADDR
	},
	{
		XPAR_BLP_CIPS_PSPMC_0_PSV_CORESIGHT_LPD_ATM_DEVICE_ID,
		XPAR_BLP_CIPS_PSPMC_0_PSV_CORESIGHT_LPD_ATM_S_AXI_BASEADDR
	}
};


