
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpiops.h"

/*
* The configuration table for devices
*/

XGpioPs_Config XGpioPs_ConfigTable[XPAR_XGPIOPS_NUM_INSTANCES] =
{
	{
		XPAR_BLP_CIPS_PSPMC_0_PSV_GPIO_2_DEVICE_ID,
		XPAR_BLP_CIPS_PSPMC_0_PSV_GPIO_2_BASEADDR
	},
	{
		XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_GPIO_0_DEVICE_ID,
		XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_GPIO_0_BASEADDR
	}
};


