
# Copyright (C) 2024 Advanced Micro Devices, Inc.    All rights reserved.
# SPDX-License-Identifier: MIT

FROM ubuntu:18.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt update

RUN apt-get update

RUN apt-get install -y xvfb tzdata locales language-pack-en rsync wget x11-utils sudo

RUN locale-gen

RUN ln -fs /usr/share/zoneinfo/America/Los_Angeles /etc/localtime && dpkg-reconfigure --frontend noninteractive tzdata

RUN dpkg --add-architecture i386

RUN mkdir -p /opt/vmr

WORKDIR /opt/vmr/

RUN cd /tmp && wget https://github.com/Xilinx/XRT/raw/master/src/runtime_src/tools/scripts/xrtdeps.sh && chmod +x xrtdeps.sh && ./xrtdeps.sh -docker

RUN groupadd hd -g 10115 && useradd -g hd xbuild -u 65673 && usermod -a -G sudo xbuild

RUN apt --fix-broken -y install
 
RUN apt-get --fix-broken -y install 

RUN apt --fix-missing -y install 

RUN apt-get --fix-missing -y install 

RUN echo "ALL ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers	

# Create dirs needed for user	
RUN mkdir -p /home/xbuild  && chmod -R a+rw /home/xbuild

ENTRYPOINT ["bash", "-c"]
