#
#  Copyright (C) 2024 Advanced Micro Devices, Inc.    All rights reserved.
#
#  Apache License Verbiage
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

# To drop into a bash shell within the container:
#   docker-compose run --rm xrt-ipu bash
# To rebuild after Dockerfile changes:
#   docker-compose build
# To stop all containers associated with this project:
#   docker-compose down
# To build xrt-ipu in docker container:
#   docker-compose run --rm xrt-ipu 

#If running the docker container from command line, please source setEnvUser.sh script to set the User environment variables
#source build/docker/setEncUser.sh

version: "3.3"
services:
  vmr-ubuntu2004:   
    network_mode: bridge        
    build:      
      args:
        ## These arguments will default to xbuild, but you can add your user in         
        # one of two ways.     
        # 1. For per project setup, add a .env file at the root of this project e.g.   
        #    cp example.env .env && vi .env < docker-compose reads .env 
        # 2. Set these environment variables per user with .bashrc or .cshrc   
        #    but most of the time these variables will already be set for you. 
        # NOTE: These variables are read at build-time and at run-time
        USER_ID: 65673   
        USER_NAME: xbuild        
        GROUP_ID: 10115   
        GROUP_NAME: hd 
      context: .        
      dockerfile: Dockerfile-vmr-ubuntu20.04
    image: "artifactory.xilinx.com/xrt-build-docker-images-local/vmr-ubuntu2004:latest"  
    volumes:
      # We mount the current project to /app
      - ../:/opt/vmr:rshared    
      - /proj/xbuilds:/proj/xbuilds:rshared
      - /proj/sdxbf:/proj/sdxbf:rshared
      - /tools:/tools:rshared 
    user: ${XDOCK_USER:-xbuild} 
    working_dir: /opt/vmr/build   
    environment:        
      - BUILD_NUMBER
      - RELEASE    
      - XRT_VERSION_PATCH=${BUILD_NUMBER}       
      - NFSPATH=${PWD}  
      - AUTH_TOKEN      
      - USER    
      - DEBREPOKEY
      - WINREPOKEY  
      - ARTIFACTORYSERVER       
      - RDI_ROOT=/opt/xrt-ipu/buildubuntu2004   
      - GRADLE_USER_HOME=/tmp/gradleubuntu2004  
      - REL_DIR=Release_ubuntu2004      
      - DEBUG_DIR=Debug_ubuntu2004      
    command: ./build.sh
