FROM artifactory.xilinx.com/xrt-build-docker-images-local/xrt-centos78

RUN mkdir -p /opt/vmr

RUN yum install -y epel-release wget sudo

RUN yum install -y centos-release-scl-rh
 
RUN yum install -y devtoolset-9

RUN yum install -y xorg-x11-server-Xvfb rsync 


RUN cd /tmp && wget https://github.com/Xilinx/XRT/raw/master/src/runtime_src/tools/scripts/xrtdeps.sh && chmod +x xrtdeps.sh && ./xrtdeps.sh -docker

#RUN groupadd hd -g 10115 && useradd -g hd xbuild -u 65673 && usermod -aG wheel xbuild

RUN yum clean all && rm -rf /var/cache/yum && echo "http_caching=none" >>/etc/yum.conf

RUN echo "ALL ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Create dirs needed for user
RUN mkdir -p /home/xbuild  && chmod -R a+rw /home/xbuild

WORKDIR /opt/vmr


ENTRYPOINT ["scl", "enable", "devtoolset-9", "--", "bash", "-c"]
