
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xrtcpsu.h"

/*
* The configuration table for devices
*/

XRtcPsu_Config XRtcPsu_ConfigTable[XPAR_XRTCPSU_NUM_INSTANCES] =
{
	{
		XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_RTC_0_DEVICE_ID,
		XPAR_BLP_CIPS_PSPMC_0_PSV_PMC_RTC_0_BASEADDR
	}
};


