#include "utt_assert_SDRs.h"

/*This Structure is created only for the purpose of asserting SDRs in UT*/
Assert_Sdr_t assertSdrData[] = {
		/* BoardInfo SDR */
		{
				.sensor_id = 1,
				.sensor_name_type_length = 13,
				.sensor_name = "Product Name",
				.sensor_value_type_length = 25,
				.sensor_value = "VCK5000-PP",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0,
			        .sensor_status = 1,
		},
		{
				.sensor_id = 2,
				.sensor_name_type_length = 11,
				.sensor_name = "Serial Num",
				.sensor_value_type_length = 15,
				.sensor_value = "XFL134CBTKZP",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0,
			        .sensor_status = 1,
		},
		{
				.sensor_id = 3,
				.sensor_name_type_length = 9,
				.sensor_name = "Part Num",
				.sensor_value_type_length = 25,
				.sensor_value = "05025-04",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0,
			        .sensor_status = 1,
		},
		{
				.sensor_id = 4,
				.sensor_name_type_length = 9,
				.sensor_name = "Revision",
				.sensor_value_type_length = 9,
				.sensor_value = "A",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0,
			        .sensor_status = 1,
		},
		{
				.sensor_id = 5,
				.sensor_name_type_length = 9,
				.sensor_name = "MFG Date",
				.sensor_value_type_length = 4,
				.sensor_value = {0xdd, 0x63, 0xcd},
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0,
			        .sensor_status = 1,
		},
		{
				.sensor_id = 6,
				.sensor_name_type_length = 5,
				.sensor_name = "UUID",
				.sensor_value_type_length = 17,
				.sensor_value = {0xe2, 0x36, 0xf9, 0x4e, 0xcf, 0xf2, 0x43, 0xe8, 0x97, 0xd3, 0x04, 0x6c, 0x77, 0xc8, 0x93, 0xaf},
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0,
			        .sensor_status = 1,
		},
		{
				.sensor_id = 7,
				.sensor_name_type_length = 6,
				.sensor_name = "MAC 0",
				.sensor_value_type_length = 7,
				.sensor_value = "",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0,
			        .sensor_status = 1,
		},
		{
				.sensor_id = 8,
				.sensor_name_type_length = 11,
				.sensor_name = "fpga_fan_1",
				.sensor_value_type_length = 2,
				.sensor_value = "A",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0,
			        .sensor_status = 1,
		},
		{
				.sensor_id = 9,
				.sensor_name_type_length = 14,
				.sensor_name = "Active SC Ver",
				.sensor_value_type_length = 4,
				.sensor_value = "",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0,
			        .sensor_status = 1,
		},
		{
				.sensor_id = 10,
				.sensor_name_type_length = 14,
				.sensor_name = "Target SC Ver",
				.sensor_value_type_length = 3,
				.sensor_value = "",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0,
			        .sensor_status = 1,
		},
		{
				.sensor_id = 11,
				.sensor_name_type_length = 7,
				.sensor_name = "OEM ID",
				.sensor_value_type_length = 5,
				.sensor_value = "",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0,
			        .sensor_status = 1,
		},
		/* Temerature SDR */
		{
				.sensor_id = 1,
				.sensor_name_type_length = 4,
				.sensor_name = "PCB",
				.sensor_value_type_length = 2,
				.sensor_value = 70,
				.sensor_base_unit_type_length = 8,
				.sensor_base_unit = "Celsius",
				.sensor_unit_modifier_byte = 0x0,
				.threshold_support_byte = 0xc7,
				.upper_fatal_limit = 95,
				.upper_critical_limit = 85,
				.upper_warning_limit = 80,
			        .sensor_status = 1,
			        .sensorAverageValue = 70,
			        .sensorMaxValue = 70,
		},
		{
				.sensor_id = 2,
				.sensor_name_type_length = 7,
				.sensor_name = "device",
				.sensor_value_type_length = 2,
				.sensor_value = 71,
				.sensor_base_unit_type_length = 8,
				.sensor_base_unit = "Celsius",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0xc7,
				.upper_fatal_limit = 107,
				.upper_critical_limit = 97,
				.upper_warning_limit = 88,
				.sensor_status = 1,
				.sensorAverageValue = 71,
				.sensorMaxValue = 71,
		},
		{
				.sensor_id = 3,
				.sensor_name_type_length = 7,
				.sensor_name = "vccint",
				.sensor_value_type_length = 2,
				.sensor_value = 60,
				.sensor_base_unit_type_length = 8,
				.sensor_base_unit = "Celsius",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0xc7,
				.upper_fatal_limit = 125,
				.upper_critical_limit = 110,
				.upper_warning_limit = 100,
				.sensor_status = 1,
				.sensorAverageValue = 60,
				.sensorMaxValue = 60,
		},
		/* Voltage SDR */
		{
				.sensor_id = 1,
				.sensor_name_type_length = 8,
				.sensor_name = "12v_pex",
				.sensor_value_type_length = 2,
				.sensor_value = {0xE0, 0x2E},     /* 12000mV*/
				.sensor_base_unit_type_length = 6,
				.sensor_base_unit = "Volts",
				.sensor_unit_modifier_byte = -3,
				.threshold_support_byte = 0xc0,
				.sensor_status = 1,
				.sensorAverageValue = {0xE0, 0x2E},
				.sensorMaxValue = {0xE0, 0x2E},
		},
		{
				.sensor_id = 2,
				.sensor_name_type_length = 8,
				.sensor_name = "3v3_pex",
				.sensor_value_type_length = 2,
				.sensor_value = {0xB8, 0x0B},      /* 3000mV*/
				.sensor_base_unit_type_length = 6,
				.sensor_base_unit = "Volts",
				.sensor_unit_modifier_byte = -3,
				.threshold_support_byte = 0xc0,
				.sensor_status = 1,
				.sensorAverageValue = {0xB8, 0x0B},
				.sensorMaxValue = {0xB8, 0x0B},
		},
                {
                                .sensor_id = 3,
                                .sensor_name_type_length = 7,
                                .sensor_name = "vccint",
                                .sensor_value_type_length = 4,
                                .sensor_value = {0x88, 0x13},   /* 5000 mV*/
                                .sensor_base_unit_type_length = 6,
                                .sensor_base_unit = "Volts",
                                .sensor_unit_modifier_byte = -3,
                                .threshold_support_byte = 0xc0,
                                .sensor_status = 1,
                                .sensorAverageValue = {0x88, 0x13},
                                .sensorMaxValue = {0x88, 0x13},
                },
		/* Current SDR */
		{
				.sensor_id = 1,
				.sensor_name_type_length = 8,
				.sensor_name = "12v_pex",
				.sensor_value_type_length = 4,
				.sensor_value = {0x88, 0x13},     /* 5000mA*/
				.sensor_base_unit_type_length = 5,
				.sensor_base_unit = "Amps",
				.sensor_unit_modifier_byte = -3,
				.threshold_support_byte = 0xc0,
				.sensor_status = 1,
				.sensorAverageValue = {0x88, 0x13},
				.sensorMaxValue = {0x88, 0x13},
		},
		{
				.sensor_id = 2,
				.sensor_name_type_length = 8,
				.sensor_name = "3v3_pex",
				.sensor_value_type_length = 4,
				.sensor_value = {0xA0, 0x0F},     /* 4000mA*/
				.sensor_base_unit_type_length = 5,
				.sensor_base_unit = "Amps",
				.sensor_unit_modifier_byte = -3,
				.threshold_support_byte = 0xc0,
				.sensor_status = 1,
				.sensorAverageValue = {0xA0, 0x0F},
				.sensorMaxValue = {0xA0, 0x0F},
		},
		{
				.sensor_id = 3,
				.sensor_name_type_length = 7,
				.sensor_name = "vccint",
				.sensor_value_type_length = 4,
				.sensor_value = {0xA0, 0x0F},     /* 4000mA*/
				.sensor_base_unit_type_length = 5,
				.sensor_base_unit = "Amps",
				.sensor_unit_modifier_byte = -3,
				.threshold_support_byte = 0xc0,
				.sensor_status = 1,
				.sensorAverageValue = {0xa0, 0x0f},
				.sensorMaxValue = {0xa0, 0x0f},
		},
		/* Power SDR */
		{
				.sensor_id = 1,
				.sensor_name_type_length = 12,
				.sensor_name = "Total Power",
				.sensor_value_type_length = 2,
				.sensor_value = {0x48},     /*72W*/
				.sensor_base_unit_type_length = 6,
				.sensor_base_unit = "Watts",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0xc0,
				.sensor_status = 1,
				.sensorAverageValue = {0x48},
				.sensorMaxValue = {0x48},
		},

};

Assert_Sdr_t pxAssertSdrDataV80[] = {
    /* BoardInfo SDR */
    {
            .sensor_id = 1,
            .sensor_name_type_length = 13,
            .sensor_name = "Product Name",
            .sensor_value_type_length = 25,
            .sensor_value = "VCK5000-PP",
            .sensor_unit_modifier_byte = 0,
            .threshold_support_byte = 0,
            .sensor_status = 1,
    },
    {
            .sensor_id = 2,
            .sensor_name_type_length = 11,
            .sensor_name = "Serial Num",
            .sensor_value_type_length = 15,
            .sensor_value = "XFL134CBTKZP",
            .sensor_unit_modifier_byte = 0,
            .threshold_support_byte = 0,
            .sensor_status = 1,
    },
    {
            .sensor_id = 3,
            .sensor_name_type_length = 9,
            .sensor_name = "Part Num",
            .sensor_value_type_length = 25,
            .sensor_value = "05025-04",
            .sensor_unit_modifier_byte = 0,
            .threshold_support_byte = 0,
            .sensor_status = 1,
    },
    {
            .sensor_id = 4,
            .sensor_name_type_length = 9,
            .sensor_name = "Revision",
            .sensor_value_type_length = 9,
            .sensor_value = "A",
            .sensor_unit_modifier_byte = 0,
            .threshold_support_byte = 0,
            .sensor_status = 1,
    },
    {
            .sensor_id = 5,
            .sensor_name_type_length = 9,
            .sensor_name = "MFG Date",
            .sensor_value_type_length = 4,
            .sensor_value = {0xdd, 0x63, 0xcd},
            .sensor_unit_modifier_byte = 0,
            .threshold_support_byte = 0,
            .sensor_status = 1,
    },
    {
            .sensor_id = 6,
            .sensor_name_type_length = 5,
            .sensor_name = "UUID",
            .sensor_value_type_length = 17,
            .sensor_value = {0xe2, 0x36, 0xf9, 0x4e, 0xcf, 0xf2, 0x43, 0xe8, 0x97, 0xd3, 0x04, 0x6c, 0x77, 0xc8, 0x93, 0xaf},
            .sensor_unit_modifier_byte = 0,
            .threshold_support_byte = 0,
            .sensor_status = 1,
    },
    {
            .sensor_id = 7,
            .sensor_name_type_length = 6,
            .sensor_name = "MAC 0",
            .sensor_value_type_length = 7,
            .sensor_value = "",
            .sensor_unit_modifier_byte = 0,
            .threshold_support_byte = 0,
            .sensor_status = 1,
    },
    {
            .sensor_id = 8,
            .sensor_name_type_length = 11,
            .sensor_name = "fpga_fan_1",
            .sensor_value_type_length = 2,
            .sensor_value = "A",
            .sensor_unit_modifier_byte = 0,
            .threshold_support_byte = 0,
            .sensor_status = 1,
    },
    {
            .sensor_id = 9,
            .sensor_name_type_length = 14,
            .sensor_name = "Active SC Ver",
            .sensor_value_type_length = 4,
            .sensor_value = "",
            .sensor_unit_modifier_byte = 0,
            .threshold_support_byte = 0,
            .sensor_status = 1,
    },
    {
            .sensor_id = 10,
            .sensor_name_type_length = 14,
            .sensor_name = "Target SC Ver",
            .sensor_value_type_length = 3,
            .sensor_value = "",
            .sensor_unit_modifier_byte = 0,
            .threshold_support_byte = 0,
            .sensor_status = 1,
    },
    {
            .sensor_id = 11,
            .sensor_name_type_length = 7,
            .sensor_name = "OEM ID",
            .sensor_value_type_length = 5,
            .sensor_value = "",
            .sensor_unit_modifier_byte = 0,
            .threshold_support_byte = 0,
            .sensor_status = 1,
    },
    /* Temerature SDR */
    {
            .sensor_id = 1,
            .sensor_name_type_length = 4,
            .sensor_name = "PCB",
            .sensor_value_type_length = 2,
            .sensor_value = 70,
            .sensor_base_unit_type_length = 8,
            .sensor_base_unit = "Celsius",
            .sensor_unit_modifier_byte = 0x0,
            .threshold_support_byte = 0xc7,
            .upper_fatal_limit = 95,
            .upper_critical_limit = 85,
            .upper_warning_limit = 80,
            .sensor_status = 1,
            .sensorAverageValue = 70,
            .sensorMaxValue = 70,
    },
    {
            .sensor_id = 2,
            .sensor_name_type_length = 7,
            .sensor_name = "vccint",
            .sensor_value_type_length = 2,
            .sensor_value = 60,
            .sensor_base_unit_type_length = 8,
            .sensor_base_unit = "Celsius",
            .sensor_unit_modifier_byte = 0,
            .threshold_support_byte = 0xc7,
            .upper_fatal_limit = 125,
            .upper_critical_limit = 110,
            .upper_warning_limit = 100,
            .sensor_status = 1,
            .sensorAverageValue = 60,
            .sensorMaxValue = 60,
    },
    {
            .sensor_id = 3,
            .sensor_name_type_length = 7,
            .sensor_name = "VCCHBM",
            .sensor_value_type_length = 2,
            .sensor_value = 60,
            .sensor_base_unit_type_length = 8,
            .sensor_base_unit = "Celsius",
            .sensor_unit_modifier_byte = 0x0,
            .threshold_support_byte = 0xc7,
            .upper_fatal_limit = 125,
            .upper_critical_limit = 110,
            .upper_warning_limit = 100,
            .sensor_status = 1,
            .sensorAverageValue = 60,
            .sensorMaxValue = 60,
    },
    {
            .sensor_id = 4,
            .sensor_name_type_length = 12,
            .sensor_name = "1V2VCCODIMM",
            .sensor_value_type_length = 2,
            .sensor_value = 60,
            .sensor_base_unit_type_length = 8,
            .sensor_base_unit = "Celsius",
            .sensor_unit_modifier_byte = 0x0,
            .threshold_support_byte = 0xc7,
            .upper_fatal_limit = 125,
            .upper_critical_limit = 110,
            .upper_warning_limit = 100,
            .sensor_status = 1,
            .sensorAverageValue = 60,
            .sensorMaxValue = 60,
    },
    {
            .sensor_id = 5,
            .sensor_name_type_length = 11,
            .sensor_name = "1V2GTXAVTT",
            .sensor_value_type_length = 2,
            .sensor_value = 60,
            .sensor_base_unit_type_length = 8,
            .sensor_base_unit = "Celsius",
            .sensor_unit_modifier_byte = 0x0,
            .threshold_support_byte = 0xc7,
            .upper_fatal_limit = 125,
            .upper_critical_limit = 110,
            .upper_warning_limit = 100,
            .sensor_status = 1,
            .sensorAverageValue = 60,
            .sensorMaxValue = 60,
    },
    {
            .sensor_id = 6,
            .sensor_name_type_length = 12,
            .sensor_name = "cage_temp_0",
            .sensor_value_type_length = 2,
            .sensor_value = 32,
            .sensor_base_unit_type_length = 8,
            .sensor_base_unit = "Celsius",
            .sensor_unit_modifier_byte = 0x0,
            .threshold_support_byte = 0xc7,
            .upper_fatal_limit = 90,
            .upper_critical_limit = 85,
            .upper_warning_limit = 80,
            .sensor_status = 1,
            .sensorAverageValue = 32,
            .sensorMaxValue = 32,
    },
    {
            .sensor_id = 7,
            .sensor_name_type_length = 12,
            .sensor_name = "cage_temp_1",
            .sensor_value_type_length = 2,
            .sensor_value = 33,
            .sensor_base_unit_type_length = 8,
            .sensor_base_unit = "Celsius",
            .sensor_unit_modifier_byte = 0x0,
            .threshold_support_byte = 0xc7,
            .upper_fatal_limit = 90,
            .upper_critical_limit = 85,
            .upper_warning_limit = 80,
            .sensor_status = 1,
            .sensorAverageValue = 33,
            .sensorMaxValue = 33,
    },
    {
            .sensor_id = 8,
            .sensor_name_type_length = 12,
            .sensor_name = "cage_temp_2",
            .sensor_value_type_length = 2,
            .sensor_value = 34,
            .sensor_base_unit_type_length = 8,
            .sensor_base_unit = "Celsius",
            .sensor_unit_modifier_byte = 0x0,
            .threshold_support_byte = 0xc7,
            .upper_fatal_limit = 90,
            .upper_critical_limit = 85,
            .upper_warning_limit = 80,
            .sensor_status = 1,
            .sensorAverageValue = 34,
            .sensorMaxValue = 34,
    },
    {
            .sensor_id = 9,
            .sensor_name_type_length = 12,
            .sensor_name = "cage_temp_3",
            .sensor_value_type_length = 2,
            .sensor_value = 35,
            .sensor_base_unit_type_length = 8,
            .sensor_base_unit = "Celsius",
            .sensor_unit_modifier_byte = 0x0,
            .threshold_support_byte = 0xc7,
            .upper_fatal_limit = 90,
            .upper_critical_limit = 85,
            .upper_warning_limit = 80,
            .sensor_status = 1,
            .sensorAverageValue = 35,
            .sensorMaxValue = 35,
    },
    /* Voltage SDR */
    {
            .sensor_id = 1,
            .sensor_name_type_length = 8,
            .sensor_name = "12v_pex",
            .sensor_value_type_length = 2,
            .sensor_value = {0xE0, 0x2E},     /* 12000mV*/
            .sensor_base_unit_type_length = 6,
            .sensor_base_unit = "Volts",
            .sensor_unit_modifier_byte = -3,
            .threshold_support_byte = 0xc0,
            .sensor_status = 1,
            .sensorAverageValue = {0xE0, 0x2E},
            .sensorMaxValue = {0xE0, 0x2E},
    },
    {
            .sensor_id = 2,
            .sensor_name_type_length = 8,
            .sensor_name = "3v3_pex",
            .sensor_value_type_length = 2,
            .sensor_value = {0xB8, 0x0B},      /* 3000mV*/
            .sensor_base_unit_type_length = 6,
            .sensor_base_unit = "Volts",
            .sensor_unit_modifier_byte = -3,
            .threshold_support_byte = 0xc0,
            .sensor_status = 1,
            .sensorAverageValue = {0xB8, 0x0B},
            .sensorMaxValue = {0xB8, 0x0B},
    },
    {
            .sensor_id = 3,
            .sensor_name_type_length = 7,
            .sensor_name = "vccint",
            .sensor_value_type_length = 4,
            .sensor_value = {0xE0, 0x2E},   /* 5000 mV*/
            .sensor_base_unit_type_length = 6,
            .sensor_base_unit = "Volts",
            .sensor_unit_modifier_byte = -3,
            .threshold_support_byte = 0xc0,
            .sensor_status = 1,
            .sensorAverageValue = {0xE0, 0x2E},
            .sensorMaxValue = {0xE0, 0x2E},
    },
    {
            .sensor_id = 4,
            .sensor_name_type_length = 12,
            .sensor_name = "1V5_VCC_AUX",
            .sensor_value_type_length = 2,
            .sensor_value = {0x19, 0x06},      /* 1561mV*/
            .sensor_base_unit_type_length = 6,
            .sensor_base_unit = "Volts",
            .sensor_unit_modifier_byte = -3,
            .threshold_support_byte = 0xc0,
            .sensor_status = 1,
            .sensorAverageValue = {0x19, 0x06},
            .sensorMaxValue = {0x19, 0x06},
    },
            {
            .sensor_id = 5,
            .sensor_name_type_length = 8,
            .sensor_name = "3V3QSFP",
            .sensor_value_type_length = 2,
            .sensor_value = {0xe4, 0x0c},      /* 3300mV*/
            .sensor_base_unit_type_length = 6,
            .sensor_base_unit = "Volts",
            .sensor_unit_modifier_byte = -3,
            .threshold_support_byte = 0xc0,
            .sensor_status = 1,
            .sensorAverageValue = {0xe4, 0x0c},
            .sensorMaxValue = {0xe4, 0x0c},
    },
            {
            .sensor_id = 6,
            .sensor_name_type_length = 8,
            .sensor_name = "12VAUX0",
            .sensor_value_type_length = 2,
            .sensor_value = {0x29, 0x2F},      /* 12073mV*/
            .sensor_base_unit_type_length = 6,
            .sensor_base_unit = "Volts",
            .sensor_unit_modifier_byte = -3,
            .threshold_support_byte = 0xc0,
            .sensor_status = 1,
            .sensorAverageValue = {0x29, 0x2F},
            .sensorMaxValue = {0x29, 0x2F},
    },
            {
            .sensor_id = 7,
            .sensor_name_type_length = 8,
            .sensor_name = "12VAUX1",
            .sensor_value_type_length = 2,
            .sensor_value = {0x2A, 0x2F},      /* 3000mV*/
            .sensor_base_unit_type_length = 6,
            .sensor_base_unit = "Volts",
            .sensor_unit_modifier_byte = -3,
            .threshold_support_byte = 0xc0,
            .sensor_status = 1,
            .sensorAverageValue = {0x2A, 0x2F},
            .sensorMaxValue = {0x2A, 0x2F},
    },
            {
            .sensor_id = 8,
            .sensor_name_type_length = 8,
            .sensor_name = "VCC_HBM",
            .sensor_value_type_length = 2,
            .sensor_value = {0x8A, 0x02},      /* 650*/
            .sensor_base_unit_type_length = 6,
            .sensor_base_unit = "Volts",
            .sensor_unit_modifier_byte = -3,
            .threshold_support_byte = 0xc0,
            .sensor_status = 1,
            .sensorAverageValue = {0x8A, 0x02},
            .sensorMaxValue = {0x8A, 0x02},
    },
            {
            .sensor_id = 9,
            .sensor_name_type_length = 14,
            .sensor_name = "1V2_VCCO_DIMM",
            .sensor_value_type_length = 2,
            .sensor_value = {0xF2, 0x4},      /* 1266mV*/
            .sensor_base_unit_type_length = 6,
            .sensor_base_unit = "Volts",
            .sensor_unit_modifier_byte = -3,
            .threshold_support_byte = 0xc0,
            .sensor_status = 1,
            .sensorAverageValue = {0xF2, 0x4},
            .sensorMaxValue = {0xF2, 0x4},
    },
            {
            .sensor_id = 10,
            .sensor_name_type_length = 12,
            .sensor_name = "1V2_GTXAVTT",
            .sensor_value_type_length = 2,
            .sensor_value = {0xF3, 0x4},      /* 1267 mV*/
            .sensor_base_unit_type_length = 6,
            .sensor_base_unit = "Volts",
            .sensor_unit_modifier_byte = -3,
            .threshold_support_byte = 0xc0,
            .sensor_status = 1,
            .sensorAverageValue = {0xF3, 0x4},
            .sensorMaxValue = {0xF3, 0x4},
    },
    /* Current SDR */
    {
            .sensor_id = 1,
            .sensor_name_type_length = 8,
            .sensor_name = "12v_pex",
            .sensor_value_type_length = 4,
            .sensor_value = {0x88, 0x13},     /* 5000mA*/
            .sensor_base_unit_type_length = 5,
            .sensor_base_unit = "Amps",
            .sensor_unit_modifier_byte = -3,
            .threshold_support_byte = 0xc0,
            .sensor_status = 1,
            .sensorAverageValue = {0x88, 0x13},
            .sensorMaxValue = {0x88, 0x13},
    },
    {
            .sensor_id = 2,
            .sensor_name_type_length = 8,
            .sensor_name = "3v3_pex",
            .sensor_value_type_length = 4,
            .sensor_value = {0xA0, 0x0F},     /* 4000mA*/
            .sensor_base_unit_type_length = 5,
            .sensor_base_unit = "Amps",
            .sensor_unit_modifier_byte = -3,
            .threshold_support_byte = 0xc0,
            .sensor_status = 1,
            .sensorAverageValue = {0xA0, 0x0F},
            .sensorMaxValue = {0xA0, 0x0F},
    },
    {
            .sensor_id = 3,
            .sensor_name_type_length = 7,
            .sensor_name = "vccint",
            .sensor_value_type_length = 4,
            .sensor_value = {0xA0, 0x0F},     /* 4000mA*/
            .sensor_base_unit_type_length = 5,
            .sensor_base_unit = "Amps",
            .sensor_unit_modifier_byte = -3,
            .threshold_support_byte = 0xc0,
            .sensor_status = 1,
            .sensorAverageValue = {0xa0, 0x0f},
            .sensorMaxValue = {0xa0, 0x0f},
    },
    {
            .sensor_id = 4,
            .sensor_name_type_length = 12,
            .sensor_name = "1V5_VCC_AUX",
            .sensor_value_type_length = 4,
            .sensor_value = {0xC6, 0x2},     /* 710mA*/
            .sensor_base_unit_type_length = 5,
            .sensor_base_unit = "Amps",
            .sensor_unit_modifier_byte = -3,
            .threshold_support_byte = 0xc0,
            .sensor_status = 1,
            .sensorAverageValue = {0xC6, 0x2},
            .sensorMaxValue = {0xC6, 0x2},
    },
    {
            .sensor_id = 5,
            .sensor_name_type_length = 8,
            .sensor_name = "3V3QSFP",
            .sensor_value_type_length = 4,
            .sensor_value = {0xD0, 0x2},     /* 720mA*/
            .sensor_base_unit_type_length = 5,
            .sensor_base_unit = "Amps",
            .sensor_unit_modifier_byte = -3,
            .threshold_support_byte = 0xc0,
            .sensor_status = 1,
            .sensorAverageValue = {0xD0, 0x2},
            .sensorMaxValue = {0xD0, 0x2},
    },
    {
            .sensor_id = 6,
            .sensor_name_type_length = 8,
            .sensor_name = "12VAUX0",
            .sensor_value_type_length = 4,
            .sensor_value = {0xDA, 0x2},     /* 730mA*/
            .sensor_base_unit_type_length = 5,
            .sensor_base_unit = "Amps",
            .sensor_unit_modifier_byte = -3,
            .threshold_support_byte = 0xc0,
            .sensor_status = 1,
            .sensorAverageValue = {0xDA, 0x2},
            .sensorMaxValue = {0xDA, 0x2},
    },
    {
            .sensor_id = 7,
            .sensor_name_type_length = 8,
            .sensor_name = "12VAUX1",
            .sensor_value_type_length = 4,
            .sensor_value = {0xE4, 0x2},     /* 740mA*/
            .sensor_base_unit_type_length = 5,
            .sensor_base_unit = "Amps",
            .sensor_unit_modifier_byte = -3,
            .threshold_support_byte = 0xc0,
            .sensor_status = 1,
            .sensorAverageValue = {0xE4, 0x2},
            .sensorMaxValue = {0xE4, 0x2},
    },
    {
            .sensor_id = 8,
            .sensor_name_type_length = 8,
            .sensor_name = "VCC_HBM",
            .sensor_value_type_length = 4,
            .sensor_value = {0xEE, 0x2},     /* 750mA*/
            .sensor_base_unit_type_length = 5,
            .sensor_base_unit = "Amps",
            .sensor_unit_modifier_byte = -3,
            .threshold_support_byte = 0xc0,
            .sensor_status = 1,
            .sensorAverageValue = {0xEE, 0x2},
            .sensorMaxValue = {0xEE, 0x2},
    },
    {
            .sensor_id = 9,
            .sensor_name_type_length = 14,
            .sensor_name = "1V2_VCCO_DIMM",
            .sensor_value_type_length = 4,
            .sensor_value = {0xF8, 0x2},     /* 5000mA*/
            .sensor_base_unit_type_length = 5,
            .sensor_base_unit = "Amps",
            .sensor_unit_modifier_byte = -3,
            .threshold_support_byte = 0xc0,
            .sensor_status = 1,
            .sensorAverageValue = {0xF8, 0x2},
            .sensorMaxValue = {0xF8, 0x2},
    },
    {
            .sensor_id = 10,
            .sensor_name_type_length = 12,
            .sensor_name = "1V2_GTXAVTT",
            .sensor_value_type_length = 4,
            .sensor_value = {0x02, 0x3},     /* 5000mA*/
            .sensor_base_unit_type_length = 5,
            .sensor_base_unit = "Amps",
            .sensor_unit_modifier_byte = -3,
            .threshold_support_byte = 0xc0,
            .sensor_status = 1,
            .sensorAverageValue = {0x02, 0x3},
            .sensorMaxValue = {0x02, 0x3},
    },
    /* Power SDR */
    {
            .sensor_id = 1,
            .sensor_name_type_length = 12,
            .sensor_name = "Total Power",
            .sensor_value_type_length = 2,
            .sensor_value = {0x48},     /*72W*/
            .sensor_base_unit_type_length = 6,
            .sensor_base_unit = "Watts",
            .sensor_unit_modifier_byte = 0,
            .threshold_support_byte = 0xc0,
            .sensor_status = 1,
            .sensorAverageValue = {0x48},
            .sensorMaxValue = {0x48},
    }
};
