
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xmbox.h"

/*
 * The configuration table for devices
 */

XMbox_Config XMbox_ConfigTable[] =
{
	{
		 XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_0_DEVICE_ID, 
		 XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_0_BASEADDR, 
		 XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_0_USE_FSL,
		 XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_0_SEND_FSL,
		 XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_0_RECV_FSL
	},
	{
		 XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_1_DEVICE_ID, 
		 XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_1_BASEADDR, 
		 XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_1_USE_FSL,
		 XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_1_SEND_FSL,
		 XPAR_BLP_BLP_LOGIC_PF_MAILBOX_IF_1_RECV_FSL
	},
};
