#include <ut/test/vmc/asdm/utt_assert_SDRs.h>

/*This Structure is created only for the purpose of asserting SDRs in UT*/
Assert_Sdr_t assertSdrData[] = {
		/* BoardInfo SDR */
		{
				.sensor_id = 1,
				.sensor_name_type_length = 13,
				.sensor_name = "Product Name",
				.sensor_value_type_length = 25,
				.sensor_value = "VCK5000-PP",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0,
			        .sensor_status = 1,
		},
		{
				.sensor_id = 2,
				.sensor_name_type_length = 11,
				.sensor_name = "Serial Num",
				.sensor_value_type_length = 15,
				.sensor_value = "XFL134CBTKZP",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0,
			        .sensor_status = 1,
		},
		{
				.sensor_id = 3,
				.sensor_name_type_length = 9,
				.sensor_name = "Part Num",
				.sensor_value_type_length = 25,
				.sensor_value = "05025-04",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0,
			        .sensor_status = 1,
		},
		{
				.sensor_id = 4,
				.sensor_name_type_length = 9,
				.sensor_name = "Revision",
				.sensor_value_type_length = 9,
				.sensor_value = "A",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0,
			        .sensor_status = 1,
		},
		{
				.sensor_id = 5,
				.sensor_name_type_length = 9,
				.sensor_name = "MFG Date",
				.sensor_value_type_length = 4,
				.sensor_value = {0xdd, 0x63, 0xcd},
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0,
			        .sensor_status = 1,
		},
		{
				.sensor_id = 6,
				.sensor_name_type_length = 5,
				.sensor_name = "UUID",
				.sensor_value_type_length = 17,
				.sensor_value = {0xe2, 0x36, 0xf9, 0x4e, 0xcf, 0xf2, 0x43, 0xe8, 0x97, 0xd3, 0x04, 0x6c, 0x77, 0xc8, 0x93, 0xaf},
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0,
			        .sensor_status = 1,
		},
		{
				.sensor_id = 7,
				.sensor_name_type_length = 6,
				.sensor_name = "MAC 0",
				.sensor_value_type_length = 7,
				.sensor_value = "",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0,
			        .sensor_status = 1,
		},
		{
				.sensor_id = 8,
				.sensor_name_type_length = 11,
				.sensor_name = "fpga_fan_1",
				.sensor_value_type_length = 2,
				.sensor_value = "A",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0,
			        .sensor_status = 1,
		},
		{
				.sensor_id = 9,
				.sensor_name_type_length = 14,
				.sensor_name = "Active SC Ver",
				.sensor_value_type_length = 4,
				.sensor_value = "",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0,
			        .sensor_status = 1,
		},
		{
				.sensor_id = 10,
				.sensor_name_type_length = 14,
				.sensor_name = "Target SC Ver",
				.sensor_value_type_length = 3,
				.sensor_value = "",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0,
			        .sensor_status = 1,
		},
		{
				.sensor_id = 11,
				.sensor_name_type_length = 7,
				.sensor_name = "OEM ID",
				.sensor_value_type_length = 5,
				.sensor_value = "",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0,
			        .sensor_status = 1,
		},
		/* Temerature SDR */
		{
				.sensor_id = 1,
				.sensor_name_type_length = 4,
				.sensor_name = "PCB",
				.sensor_value_type_length = 2,
				.sensor_value = 70,
				.sensor_base_unit_type_length = 8,
				.sensor_base_unit = "Celsius",
				.sensor_unit_modifier_byte = 0x0,
				.threshold_support_byte = 0xc7,
				.upper_fatal_limit = 95,
				.upper_critical_limit = 85,
				.upper_warning_limit = 80,
			        .sensor_status = 1,
			        .sensorAverageValue = 70,
			        .sensorMaxValue = 70,
		},
		{
				.sensor_id = 2,
				.sensor_name_type_length = 7,
				.sensor_name = "device",
				.sensor_value_type_length = 2,
				.sensor_value = 71,
				.sensor_base_unit_type_length = 8,
				.sensor_base_unit = "Celsius",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0xc7,
				.upper_fatal_limit = 107,
				.upper_critical_limit = 97,
				.upper_warning_limit = 88,
				.sensor_status = 1,
				.sensorAverageValue = 71,
				.sensorMaxValue = 71,
		},
		{
				.sensor_id = 3,
				.sensor_name_type_length = 7,
				.sensor_name = "vccint",
				.sensor_value_type_length = 2,
				.sensor_value = 60,
				.sensor_base_unit_type_length = 8,
				.sensor_base_unit = "Celsius",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0xc7,
				.upper_fatal_limit = 125,
				.upper_critical_limit = 110,
				.upper_warning_limit = 100,
				.sensor_status = 1,
				.sensorAverageValue = 60,
				.sensorMaxValue = 60,
		},
		/* Voltage SDR */
		{
				.sensor_id = 1,
				.sensor_name_type_length = 8,
				.sensor_name = "12v_pex",
				.sensor_value_type_length = 2,
				.sensor_value = {0xE0, 0x2E},     /* 12000mV*/
				.sensor_base_unit_type_length = 6,
				.sensor_base_unit = "Volts",
				.sensor_unit_modifier_byte = -3,
				.threshold_support_byte = 0xc0,
				.sensor_status = 1,
				.sensorAverageValue = {0xE0, 0x2E},
				.sensorMaxValue = {0xE0, 0x2E},
		},
		{
				.sensor_id = 2,
				.sensor_name_type_length = 8,
				.sensor_name = "3v3_pex",
				.sensor_value_type_length = 2,
				.sensor_value = {0xB8, 0x0B},      /* 3000mV*/
				.sensor_base_unit_type_length = 6,
				.sensor_base_unit = "Volts",
				.sensor_unit_modifier_byte = -3,
				.threshold_support_byte = 0xc0,
				.sensor_status = 1,
				.sensorAverageValue = {0xB8, 0x0B},
				.sensorMaxValue = {0xB8, 0x0B},
		},
                {
                                .sensor_id = 3,
                                .sensor_name_type_length = 7,
                                .sensor_name = "vccint",
                                .sensor_value_type_length = 4,
                                .sensor_value = {0x88, 0x13},   /* 5000 mV*/
                                .sensor_base_unit_type_length = 6,
                                .sensor_base_unit = "Volts",
                                .sensor_unit_modifier_byte = -3,
                                .threshold_support_byte = 0xc0,
                                .sensor_status = 1,
                                .sensorAverageValue = {0x88, 0x13},
                                .sensorMaxValue = {0x88, 0x13},
                },
		/* Current SDR */
		{
				.sensor_id = 1,
				.sensor_name_type_length = 8,
				.sensor_name = "12v_pex",
				.sensor_value_type_length = 2,
				.sensor_value = {0x88, 0x13},     /* 5000mA*/
				.sensor_base_unit_type_length = 5,
				.sensor_base_unit = "Amps",
				.sensor_unit_modifier_byte = -3,
				.threshold_support_byte = 0xc0,
				.sensor_status = 1,
				.sensorAverageValue = {0x88, 0x13},
				.sensorMaxValue = {0x88, 0x13},
		},
		{
				.sensor_id = 2,
				.sensor_name_type_length = 8,
				.sensor_name = "3v3_pex",
				.sensor_value_type_length = 2,
				.sensor_value = {0xA0, 0x0F},     /* 4000mA*/
				.sensor_base_unit_type_length = 5,
				.sensor_base_unit = "Amps",
				.sensor_unit_modifier_byte = -3,
				.threshold_support_byte = 0xc0,
				.sensor_status = 1,
				.sensorAverageValue = {0xA0, 0x0F},
				.sensorMaxValue = {0xA0, 0x0F},
		},
		{
				.sensor_id = 3,
				.sensor_name_type_length = 7,
				.sensor_name = "vccint",
				.sensor_value_type_length = 2,
				.sensor_value = {0xA0, 0x0F},     /* 4000mA*/
				.sensor_base_unit_type_length = 5,
				.sensor_base_unit = "Amps",
				.sensor_unit_modifier_byte = -3,
				.threshold_support_byte = 0xc0,
				.sensor_status = 1,
				.sensorAverageValue = {0xa0, 0x0f},
				.sensorMaxValue = {0xa0, 0x0f},
		},
		/* Power SDR */
		{
				.sensor_id = 1,
				.sensor_name_type_length = 12,
				.sensor_name = "Total Power",
				.sensor_value_type_length = 2,
				.sensor_value = {0x48},     /*72W*/
				.sensor_base_unit_type_length = 6,
				.sensor_base_unit = "Watts",
				.sensor_unit_modifier_byte = 0,
				.threshold_support_byte = 0xc0,
				.sensor_status = 1,
				.sensorAverageValue = {0x48},
				.sensorMaxValue = {0x48},
		},

};
