
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xbram.h"

/*
* The configuration table for devices
*/

XBram_Config XBram_ConfigTable[] =
{
	{
		XPAR_ULP_PLRAM_CTRL_DEVICE_ID,
		XPAR_ULP_PLRAM_CTRL_DATA_WIDTH,
		XPAR_ULP_PLRAM_CTRL_ECC,
		XPAR_ULP_PLRAM_CTRL_FAULT_INJECT,
		XPAR_ULP_PLRAM_CTRL_CE_FAILING_REGISTERS,
		0,
		XPAR_ULP_PLRAM_CTRL_UE_FAILING_REGISTERS,
		0,
		XPAR_ULP_PLRAM_CTRL_ECC_STATUS_REGISTERS,
		XPAR_ULP_PLRAM_CTRL_CE_COUNTER_WIDTH,
		XPAR_ULP_PLRAM_CTRL_ECC_ONOFF_REGISTER,
		XPAR_ULP_PLRAM_CTRL_ECC_ONOFF_RESET_VALUE,
		XPAR_ULP_PLRAM_CTRL_WRITE_ACCESS,
		XPAR_ULP_PLRAM_CTRL_S_AXI_BASEADDR,
		XPAR_ULP_PLRAM_CTRL_S_AXI_HIGHADDR,
		XPAR_ULP_PLRAM_CTRL_S_AXI_CTRL_BASEADDR,
		XPAR_ULP_PLRAM_CTRL_S_AXI_CTRL_HIGHADDR
	}
};


