
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xintc.h"


extern void XNullHandler (void *);

/*
* The configuration table for devices
*/

XIntc_Config XIntc_ConfigTable[] =
{
	{
		XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_DEVICE_ID,
		XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_BASEADDR,
		XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_KIND_OF_INTR,
		XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_HAS_FAST,
		XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_IVAR_RESET_VALUE,
		XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_NUM_INTR_INPUTS,
		XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_ADDR_WIDTH,
		XIN_SVC_SGL_ISR_OPTION,
		XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_TYPE,
		{
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			},
			{
				XNullHandler,
				(void *) XNULL
			}
		},
		XPAR_BLP_BLP_LOGIC_ERT_SUPPORT_AXI_INTC_0_31_NUM_SW_INTR
	}
};

