
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xuartpsv.h"

/*
* The configuration table for devices
*/

XUartPsv_Config XUartPsv_ConfigTable[XPAR_XUARTPSV_NUM_INSTANCES] =
{
	{
		XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_0_DEVICE_ID,
		XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_0_BASEADDR,
		XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_0_UART_CLK_FREQ_HZ,
		XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_0_HAS_MODEM,
		XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_0_BAUDRATE
	},
	{
		XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_1_DEVICE_ID,
		XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_1_BASEADDR,
		XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_1_UART_CLK_FREQ_HZ,
		XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_1_HAS_MODEM,
		XPAR_BLP_CIPS_PSPMC_0_PSV_SBSAUART_1_BAUDRATE
	}
};


